### ISSUE TITLE
"Cannot access song files!"

### ISSUE THREAD

**Issue by molecular** [CDrummond/cantata#1014]
Hi there!

Firstly: huge kudos on cantata. I've been looking for a while and all mpd clients I have evaluated had severe shortcomings for my use cases. Cantata doesn't and on top it looks awesome and the gui is fresh and highly usable. You seem to have managed to overcome mpd protocol shortcomings way better than the alternatives, too. So: congratulations and a big thank you!

There's one issue I'm still fighting: I'd like to get album covers from file storage and cantata seems to support that. However, it doesn't seem to work (no album art on albums that have cover.jpg in file storage) and I get a hint why when I select the "Organize Files" function on an album. Cantata gives me an error popup saying: "Cannot access song files!":

![image](https://cloud.githubusercontent.com/assets/589745/25576924/b62a4380-2e62-11e7-9614-0ff053c0e3d8.png)

So I figure there's some issue with accessing the remote files. I have mounted those (they're on a server, neither the mpd machine nor the local machine) using sshfs to /home/nick/mnt/blackbox/m. I can select this folder in cantata preferences just fine and cantata sees the directories and files contained:

![image](https://cloud.githubusercontent.com/assets/589745/25576947/f0da85d0-2e62-11e7-9b60-36831cce7369.png)

There's nothing further on the stdout or anything, so I'm having a hard time figuring out exactly what's wrong.

So: how can I debug this issue and/or fix it? Is there a log file somewhere that could give further hints?

Any help appreciated.

**Comment by CDrummond** [comment]
MPD only sends Cantata the **relative** path to the songs files **within** its music_directory. So, if you have:

1. music_directory = /var/lib/mpd
2. A music flle, /var/lib/mpd/Artist/Album/Track.mp3

MPD **only** sends Cantata 'Artist/Album/Track.mp3 You would then need to configure Cantata's 'Music folder' to /var/lib/mpd Cantata adds the two paths (its 'Music folder' and the MPD file path) to ascertain the absolute path to the song file.

So, if you have:

1. Server has your music located in (e.g.) /home/mpd/music/ - and this is MPD's music_directory
2. You mount  /home/mpd to /home/user/sshs/mpd

Now to access /home/mpd/music/CoolArtist/AlbumX/Track2.mp3 Cantata would need to have '/home/user/sshfs/mpd/music' as its 'Music folder' This is because MPD will only tell Cantata that the file path is 'CoolArtist/AbumX/Track2.mp3' And the file is accessible at the sshfs mount at /user/sshfs/mpd/music/CoolArtist/AbumX/Track2.mp3

**Comment by molecular** [comment]
ah, ok! I made a mistake. Had to remove the "/m" from the Music Folder path in cantata.

Thanks a ton!!!

btw: do you have a bitcoin (or other cryptocurrency) donation address?
