### ISSUE TITLE
Sorting classical music

### ISSUE THREAD

**Issue by phggrue** [CDrummond/cantata#1025]
I love cantata, but sorting classical music doesn't do as it should.
Maybe only a little problem for you to fix it..............
I have set the composer support under tweaks.
Group by artist, sort album by name the composer is shown but sorted by artist.
Group by album, sort album by name the titles are not sorted by track number, they are sorted by composer - if the composer support is not set the are sorted by Artist.
![sort by artist](https://user-images.githubusercontent.com/29356076/27012419-c26c0e52-4ecf-11e7-815c-06a100b81192.png)
![sort by album](https://user-images.githubusercontent.com/29356076/27012422-cb89266e-4ecf-11e7-9389-a995aed823b5.png)
![playlist track numbers](https://user-images.githubusercontent.com/29356076/27012424-d04944b8-4ecf-11e7-9374-dfc1344add2f.png)
![playlist track numbers they should be](https://user-images.githubusercontent.com/29356076/27012427-d618d444-4ecf-11e7-834d-f4c27ff709f0.png)
I hope you understand it better with the screenshots.
If you can manage it all (mpd)classic lovers will love you! (A group by composer would be perfect) 
Thanks to you!!

**Comment by phggrue** [comment]
Seems to be more a grouping problem when group by album, not a sorting problem of the track numbers. It groups by album + composer.
![group by album](https://user-images.githubusercontent.com/29356076/27012681-f2de0de2-4ed4-11e7-8d12-e172001ab4e0.png)

**Comment by phggrue** [comment]
I closed it by error - soory!

**Comment by CDrummond** [comment]
Sorry, I'm not seeing this. Whilst I do not use composer support I have done the following:
1. I have two albums, one by 'Magnum' and one by 'Iron Maiden'
2. With no composer support, the are sorted 'Iron Maiden', 'Magnum'
3. Created a fake genre 'Abc'
4. Edited an album by 'Magnum', and set composer to 'Tony Clarkin'
5. Edited an album by 'Iron Maiden' and set composer to 'Wibble'
6. Set Cantata to use composer for 'Abc'
7. Refreshed DB in Cantata.
8. Now Cantata sorts 'Tony Clarkin', 'Wibble' - as expected.

Have you refreshed Cantata's DB when changing the composer tweak?

.....actually after this, I've just noticed that 'Artist Sort' is used. Do your songs have an 'Artist Sort' tag? If so, then this is used first. I've just fixed the code to always use the composer field if set in tweaks (for songs that are in the genre and have composer)

As to the album grouping, Cantata will group by artist ID and album ID. Where

Artist ID = Composer (if song is in composer genres, and has a composer), AlbumArtist (if set), Artist otherwise

Album ID = MusicBrainz album id (if tag set, and MPD configured to use this), album name otherwise

**Comment by phggrue** [comment]
Thank you for your reply.
Of course I refreshed the DB and then closed Cantata and start it again as
described in the Tweaks.
I don't know what you mean with 'Artist Sort' tag - that it sorts other
than by Artist name? I don't use this - only under tweaks that the 'The' is
not used for sorting.
I have many Rock, Blues etc. albums too in my library - everything is
working fine with group by album, always as expected.
I think this is because normaly the Artist is the same for an album and
it's rarely that someone sets the Composer on this kind of albums.
If you group albums by album + Artist (or Composer) nothing happens - the
songs are sorted 1,2,3,4 etc.
But on Classical Albums it is normal that you have different artists on
different songs in one album - or different composers in one album and
sometimes both are different from song to song. If you group classical
albums by album + artist (or composer) then you have for every artist (or
composer) on this album 1 album- if you copy this to the playlist the
tracks numbers are not sorted. I think the easiest way to fix this would be
to be able to sortb the playlist by Track number. Ok, if you have more than
1 album in the playlist it makes no sence.
Thanks again - I love Cantata.



2017-06-11 21:12 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Arist sort (or rather Album Artist Sort) is a tag that can be used to specifically set the sort. e.g. AlbumArtist="Eric Clapton" with no AlbumArtistSort would place this amongst other starting with "E". But if AlbumArtistSort was set to "Clapton, Eric" then Cantata would still display "Eric Clapton" but it will be amongst those staring with "C"

Not sure why you are mentioning "playlist" - because your first screenshot is from the Library view. If you mean the playqueue - as in the list of songs currently playing, this is sorted in the order you add them to MPD.

Anyway, if you have an album with multiple composers - then Cantata will split this up. Cantata cannot group by just Album name - multiple artists have albums called "Greatest Hits".

If you have:

AlbumName: Al
AlbumArtist: Ar
Track1 Composer: C1
Track2 Composer: C2

How do you expect the album to be grouped? If you want to group by composer - then it will split.

**Comment by phggrue** [comment]
Thanks a lot.
I meant playque - some times easy english words do not come in my mind,
sorry.
What I would like is that it only groups the AlbumName and then sorted
Tracknumbers( 1,2,3 etc), but this seems not to be possible in library view
as you say.
And it is nice to see what composers are on an album - but when I put it to
the playque the tracks are not sorted 1,2,3........ they are sorted by
composer.
I can sort them manualy, no problem for 5-6 tracks, but some albums have
15-20 or more tracks.
So it would be very comfortable if I could sort the playlist by Tracknumber
- that's all. I know normaly this does not make sense - if you have several
albums in the playque the Tracks are sorted 1,1,1,2,2,2,3,3,3 etc. But if
there is only 1 album and it's classic it makes sense.
If you can manage this...perfect. If not I will sort them manualy and then
make a playlist named by the album name - but I think there are several
hundreds of this kind in my library.
Thanks for your efforts - Cantata (and MPD) are realy wonderful.





2017-06-12 19:27 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
First of all - don't worry about your English, I'm 100% sure its better than I would be in your language :-)

No, as stated I cannot group only by album name - as multiple artists have albums with the same name.

Anyway, what I think the issue is:

1. You have an album with multiple composers, in Cantata's Library view this is split into multiple albums, e.g.
    Composer A
        Album A
            Track 1
            Track 3
    Composer B
        Album A
            Track 2
            
2. When you add these "Albums" to the play queue, Cantata adds them as "Track 1, Track 3, Track 2" - because, as far as Cantata is aware they are from different albums.

I can add "Track number" to the "Sort By" context menu - which would achieve a work-around for this. However, you would still have multiple entries in the Library for each album. 

There is not much I can do about splitting the album when grouping by "Genre" or "Artist" - as these must group tracks by artist/composer + album. However, I think when grouping by just "Album" - I could group based upon "Music brainz album id" if this is set, falling back to artist/composer + album if not. I cannot just group by name - as even for classical music I would image it is very likely to have 2 albums with the same name. This would mean you would need to tag your split albums with the "musicbrainz album id" field (MP3 tagname is "musicbrainz album id"), and configure MPD to use this (metadata_to_use needs to include "musicbrainz_albumid") - then refresh Cantata. "Music brainz album id" should be unique to each album, so it should be safe to use this to group tracks.

**Comment by phggrue** [comment]
If there is a 'Sort By' Tracknumber in the playque then I am happy!!!
That I will have multiple entries in the Library for each album(with
different composers) is absolute no problem for me - it's interesting for
me to see the composers on an album.
I think this way it's realy usefull for classic music - if I want to look
for an artist I can use the search.
So big, big thanks to you!! (Now I have to tag the Composers in a better
way - Bach JS, Bach J.S., Bach, JS, Bach Johann Sebastian.........!!)

2017-06-13 13:12 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Implemented in git/master for 2.1.0 Any chance you can checkout and compile?

**Comment by phggrue** [comment]
Tomrrow we have a free day - I will try, never done compiling before, I
only install and update in Linux. I am running Cantata on MacOS, but I have
a Laptop with Arch and Mint.
Mint should be easier. I will send you an e-mail. Many, many thanks to you
-  for the nice conversation too.

2017-06-13 19:49 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
I'll re-open for now.

**Comment by CDrummond** [comment]
I'll re-open for now. It it helps, I can probably build a quick MacOS release - but might take a day or two.

**Comment by phggrue** [comment]
Yes, I failed with compiling: "-- Could NOT find Taglib (missing:
 TAGLIB_INCLUDES TAGLIB_LIBRARIES)
CMake Error at CMakeLists.txt:207 (find_package):
  By not providing "FindQt5Widgets.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Qt5Widgets", but CMake did not find one.............."
It would be absolutely nice if you could make a MacOS release and, take all
time for it you want. I am a bit ashamed, you have done all this great work
and then I say "But there is a (little) problem with Classic Music" 75% of
my music is not classical and it's perfect!!


2017-06-14 11:34 GMT+02:00 CraigD <notifications@github.com>:

**Comment by CDrummond** [comment]
Never used this site before, but... I've uploaded a pre-release version to: https://expirebox.com/download/7b52d9dae616b22bd824d5a1daa31182.html

This link will only last for 48hrs.

**Comment by phggrue** [comment]
Whow! That's great! Composers are sorted perfectly when grouped by artist
and group by album is fantastic!
I made some screenshots so you can see it. Look at 'Altre Folie' (group by
album)- it's only 1 album with all the composers shown!
[image: Inline-Bild 4]



[image: Inline-Bild 2]
Then the Playque before sort by tracknumber - and then after sort by
tracknumber
[image: Inline-Bild 5]
And then Donizetti where he belongs to (I have to retag Donizetti G.):
[image: Inline-Bild 6]
I think Cantata is now very, very usefull for Classic Music, the most
Classic fans are Composer orientated and if someone is looking for a
specific artist he can use the search function.
And if someone want's a certain album to be grouped by artist he could set
the genre to ClassicalArtist or what ever!

So what can I say - real big thanks to you, it's fantastic!

with best wishes

PHG


2017-06-15 18:09 GMT+02:00 CraigD <notifications@github.com>:

**Comment by phggrue** [comment]
missing screenshots:
![bildschirmfoto 2017-06-16 um 22 24 41](https://user-images.githubusercontent.com/29356076/27243664-3dae1850-52e3-11e7-8f3b-85c0b5dbf389.png)
![bildschirmfoto 2017-06-16 um 22 25 20](https://user-images.githubusercontent.com/29356076/27243675-48d2c208-52e3-11e7-89b8-428c7b26dca5.png)
![bildschirmfoto 2017-06-16 um 22 25 44](https://user-images.githubusercontent.com/29356076/27243679-4e1b66c0-52e3-11e7-8442-f4ba50a295a4.png)
![bildschirmfoto 2017-06-16 um 22 27 04](https://user-images.githubusercontent.com/29356076/27243685-55eb9334-52e3-11e7-9676-c3809ee1424a.png)
