### ISSUE TITLE
Default media hotkeys

### ISSUE THREAD

**Issue by peterLaurence** [CDrummond/cantata#1070]
Hi,

First, thanks for your amazing work on Cantata.
I have a little issue : it seems that the default media hotkeys (play/pause/play next and play previous) aren't recognized. I know hotkeys can be defined for that purpose but i expected that those media hotkeys would work out of the box.
Am i missing something?

(I am on Ubuntu 16.04)

**Comment by CDrummond** [comment]
When reporting issues, the version of Cantata is always helpful :-)

Anyway, I assume this is with 2.1.0... Cantata uses the GNOME media keys daemon to interface with the media keys. The GNOME devs fixed an issue with their API, so I changed Cantata to use the correct version. This caused it to not work with older daemons. For 2.2.0 I have reverted this, so that it will work with old and new. Sorry for this.
