### ISSUE TITLE
No tray icon under lxqt

### ISSUE THREAD

**Issue by edwardtulane** [CDrummond/cantata#1089]
I am using the latest cantata git version on an arch linux machine with the lxqt desktop and the kwin window manager.

Now, I would like to activate the tray icon, but that is not even shown as an option in the preferences (I vaguely remember that it was working at some point). From what I understand browsing the latest commits, this requires the org.kde.StatusNotifierWatcher to be running. As I have some KDE components installed (because of kwin), I can start this service by hand (in ksystemsettings) and then the tray icon works just fine. 

Is that KDE service really necessary or could you resort to some dbus process that is running under lxqt anyway?
Thank you so much!

**Comment by CDrummond** [comment]
Sorry, don't use lxqt. Cantata uses Qt's system tray icon code. As of 2.2.0, the option to use the system tray icon is only presented f the "org.kde.StatusNotifierWatcher" DBUS service is registered. This is so that the option is hidden under GNOME shell if the relevant extension is not loaded.

**Comment by SpartanJ** [comment]
Is there any technical issue that prevents to keep the old XEmbed tray support enabled? I also updated to 2.2.0 and saw that the systray icon isn't there anymore. I would like to help to keep Xembed tray support if that's possible. I'm pretty sure i'm not the only one depending on the old tray support.
Thanks.

**Comment by edwardtulane** [comment]
I don't know if this applies to your situation nor whether this is a particularly elegant solution, but I found a simple workaround: At startup, I am running [this python script](https://github.com/Cairo-Dock/cairo-dock-plug-ins/blob/master/Status-Notifier/watcher/status-notifier-watcher.py), which provides a fake KDE watcher. 
Works like a charm.

**Comment by SpartanJ** [comment]
@edwardtulane Thank you very much! I'll try it later. But i also would like to keep the XEmbed support on Cantata if that's still possible.

**Comment by SpartanJ** [comment]
@edwardtulane I looked at the script and actually works just because a coincidence, but it'll break all your KDE apps systray as a consequence. What actually happens is that cantata 2.2.0 enables the systray if dbus `org.kde.StatusNotifierWatcher` is subscribed and then proceeds to create the systray as always did, with QSystemTrayIcon, which will use the systray specification available in that moment, in out case fallbacks to XEmbed automatically.
I've been reading cantata code to understand why this change was made and i think it was because a incorrect initialization of the systray icon in plasma shell when cantata starts before plasmashell is available, in that case seems to fail for some reason ( at least that's what the comment in the code says, i actually also use cantata with plasma and preload it and it's working fine ).
I don't see a real reason to stop creating the systray icon in ANY case, unless the user disables it in the configuration. I did some testing about this. I wanted to know if there's any problem when you create the systray icon if no systray is available and it just works, i think the real solution here is just always create it in Linux unless the user disables it. This will work for everyone and won't cause any troubles. For the moment i just patched cantata locally to work that way.

I'll also leave the proposal patch: [cantata.systray.patch.txt](https://github.com/CDrummond/cantata/files/1354366/cantata.systray.patch.txt)

**Comment by CDrummond** [comment]
I've changed the code to only check for the DBUS interface if run under Gnome. Does it now work OK with lxqt?

**Comment by SpartanJ** [comment]
Does the job for me! Thanks! =)

**Comment by edwardtulane** [comment]
Alright, works for me, as well! Thank you!

**Comment by CDrummond** [comment]
Thanks for the confirmations. And sorry for the original issue :-(
