### ISSUE TITLE
[feature request] physically deleting folder's/album's/track's

### ISSUE THREAD

**Issue by ww7** [CDrummond/cantata#1094]
With keyboard shortcut and mouse context menu.

**Comment by ww7** [comment]
OS: macOS. Custom actions not work, even shell commands.

**Comment by CDrummond** [comment]
Linux builds already have this feature - its connected with device support. I had a quick look to see how feasible it would be to make this independent, and while it would be possible, it's a non-trivial amount of work. Therefore, to enable this I'd have to add device support (MTP devices, UMS devices, AudioCD, etc) to macOS builds - and I just don't have the time for this.

Sorry, but macOS is not an OS I actively use.

**Comment by CDrummond** [comment]
Also, as to custom actions - just tried, and they seem to work fine. (I tried a simple `open %d` command - and this opened Finder at the correct location). For the actions to work Cantata needs to be configured correctly. To use an action, Cantata needs access the folder where your music is stored. 

When MPD gives a path to a music file to Cantata, it only passes part of the path. Consider the following scenario:

1. MPD installed on a raspberry pi
2. Music is in `/home/pi/music`
3. MPD's  `music_directory` is set to `/home/pi/music`
4. You have `/home/pi/music/Artist/Album/Track.mp3`
5. When Cantata queries MPD for the list of files, MPD returns `Artist/Album/Track.mp3` - i.e. it only returns the part of the path **within** `music_directory`
6. On your mac you have mounted (via samba) `/home/pi` to `/Volumes/pi`
7. Now the path (on the mac, where Cantata runs) of the track is `/Volumes/pi/music/Artist/Album/Track.mp3`
8. Cantata, therefore, needs to have its music folder set to `/Volumes/pi/music`

**Comment by CDrummond** [comment]
Having said all of the above - Cantata is open source, so I would happily accept a pull request to add device support to mac builds.

**Comment by ww7** [comment]
Cantata is really great on macOS too, I happy with this finding.
Custom actions works, but only when selected track, but not with folder (album).
(i not mean %d, is Ok) On the Linux same situation?
Deleting physically in keyboard shortcuts is not in plans? (ncmpcpp as able to this)
Thank You!

**Comment by CDrummond** [comment]
As stated - Cantata already supports deleting files, etc. **But** this is intertwined with the device support code - as it uses some of its features, dialogs, etc. Perhaps not ideal, but it works. I did have a quick look into just adding the deletion, but it was going to be more than a couple line change. Also, not sure if its worth the hassle to have the facility to delete music, but none to add (which is why the whole device support would need to be added).

I couldn't care less what other clients do - different code, etc. 

I use Linux exclusively - the macOS port only happened when I briefly had a MacBook. Likewise, the windows port was just to see how easy it would be. I use neither OS, hence they are not feature complete with the Linux builds - I personally have no time for this.
