### ISSUE TITLE
Scroll to current album in view

### ISSUE THREAD

**Issue by sanyarnd** [CDrummond/cantata#1098]
I have many albums (by many I mean 40+ screen pages) and there's one thing that makes me little frustrated when using Cantata.
Each time I close the player, it remembers current playlist, but it does not remember scroll position of album in view. so I have to scroll up and down to find current album playing in the grid view.
There's a way to jump to current song position in the playlist (> button), but there's none for album view.
Also it'd be great to have this behaviour when program opens.

**Comment by CDrummond** [comment]
This is not something I think most users would expect - I'd expect an app to always start in the same state. Also, it would need syncing up with being the first loading of the playqueue, etc. Possible, but too much for now.

However, Cantata already had the facility to locate a track in the library. I've extended this so that you can locate artist or album. These actions can have a short-cut assigned (although none by default). This will allow you to start Cantata, select track in playqueue, then locate the album.
