### ISSUE TITLE
Sql hangs on Library auto-search while typing

### ISSUE THREAD

**Issue by nommer** [CDrummond/cantata#1144]
Related to #1130 (Sql executed too early) where some users saw a core-dump, others had no problem, possibly depending on how large and repetitive a db was to be searched.

With a very large and/or repetitive database, if the text of the search string isn't entered quickly enough the search is off to the races looking for a single character or two, which can take a very, very long time, especially on slower hardware where further keyboard input is suspended until the over-eager search is completed. It's the only flaw I can find in an otherwise brilliant program.

Is there the possibility in future of a choice set in preferences between search-while-typing and manual entry (compose the search string, then hit the Enter key)? Or perhaps some minor delay added to the existing search method on behalf of slow typists with large databases on less than lightning-fast hardware?

**Comment by CDrummond** [comment]
This is not related to the SQL crash - that was an issue with using the class.

The search is not performed immediately (for all views). If you only enter a single character, the search is delayed for 1 second. 0.75s for 2..3 characters. 0.5s otherwise. e.g. There is a delay after the *last* keypress before the search is performed.

For the library view, at least 3 characters are required for search. Hence here, the search is delay for 0.5s before being performed. Perhaps this delay can be increased? If you can build from source, please try editing widgets/itemview.cpp and change line 1517 from `searchTimer->start(len<2 ? 1000 : len<4 ? 750 : 500);` to `searchTimer->start(1000);` This will delay all for 1 second. Does this help?

How many tracks do you have in your DB? I have ~10,000 and Cantata is more than quick enough on my laptop.

**Comment by CDrummond** [comment]
I've updated git/master to make the de-bounce delay depend upon the track count. For <= 12500 its 1second, <=18000 its 1.5seconds, 2seconds otherwise. 

Does this help?

**Comment by nommer** [comment]
An elegantly simple solution, thanks. Even with my shameless <78000 tracks, 2 seconds should be ample.

**Comment by CDrummond** [comment]
I'll close this then.
