### ISSUE TITLE
HTTP Stream on Windows

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#1174]
I hope its ok to ask such questions here as I found no other way to ask.
Does the Windows build support this, which codecs are aviable?

**Comment by CDrummond** [comment]
Windows builds use QtMultimedia libraries. As to which backend this actually uses, and what codecs are supported - I have no idea.

The windows and macOS ports are not priorities for me. I use neither of these OSs, and only ported the code to see how easy it would be.

**Comment by Thaodan** [comment]
Ok, so at least http streaming is enabled?

**Comment by CDrummond** [comment]
AFAIK, yes. As stated, I don't use this build. Anyway, why not just download and see for yourself?

**Comment by Thaodan** [comment]
I tried but playback didn't really worked and the option --debug wasn't working.  Also the readme states that http streaming is disabled.

I'm not using windows myself it's just my girlfriend's pc.

**Comment by CDrummond** [comment]
The `--debug` is for master (2.3.0, when it is released). Current release builds needs to use the `CANTATA_DEBUG` env var - see https://github.com/CDrummond/cantata/blob/2.1/README. e.g. for windows:

1. Open `cmd.exe`
2. `set CANTATA_DEBUG=0x00080000`
3. Run `cantata` from wherever it is installed in `c:\Program Files`
4. Log file will be in `C:\Users\USERNAME\AppData\Local\mpd\cantata\cache\cantata.log`

The README is probably out of date. AFAIR, since 2.0.0 HTTP stream playback has been enabled by default - for all builds. Not sure how QtMultiMedia works under windows, and how it uses the underlying media framework. Must admit I have **never** tried this under windows.

**Comment by Thaodan** [comment]
It always complains about "defaultServiceProvider::requestService(): no service found for - "org.qt-project.qt.mediaplayer"

**Comment by CDrummond** [comment]
Not on windows at the moment, and no access. Can you extract the 2 dll's from the following zip: [cantata-windows-audio.zip](https://github.com/CDrummond/cantata/files/1669046/cantata-windows-audio.zip)

Place these in `c:\Program Files (x86)\Cantata\mediaservice` (You will need to create the `mediaservice` folder). (Assuming you have Cantata installed to `c:\Program Files (x86)\Cantata`)

If you restart Cantata, does it now work?

**Comment by Thaodan** [comment]
>If you restart Cantata, does it now work?
yes, fixed thanks.

**Comment by CDrummond** [comment]
Thanks for the confirmation. I've added these to the config files for the installer, so they should be in 2.3.0
