### ISSUE TITLE
Rely more on icon theme (Linux)

### ISSUE THREAD

**Issue by Scrumplex** [CDrummond/cantata#1236]
Cantata should rely more on the user's icon theme than own icons. This should be managed with a CMAKE flag which is enabled by default on Linux systems.

**Comment by CDrummond** [comment]
Nope.

**Comment by Scrumplex** [comment]
Why though?

**Comment by CDrummond** [comment]
Because I don't want it that way. Previously Cantata had code to load system icons, with a set of fallbacks, etc. And it was becoming a pain.

I don't personally like the breeze icons, and I wanted to use monochrome icons for the main ui. Therefore, the only place where system icons would be used is the preferences dialog - and its just not worth the hassle.
