### ISSUE TITLE
'Delete song' action does not work

### ISSUE THREAD

**Issue by mykbas** [CDrummond/cantata#1259]
I enabled delete action in settings, but selecting 'Delete song' on file is not working, it just ignores the command silently. Tested on Kubuntu 18.04

**Comment by CDrummond** [comment]
Just tried, and it does indeed work. This is a setup issue in your system. Probably your music directory set in MPD is not the same as Cantata's music folder setting.

**Comment by slyx101** [comment]
I believe the issue is whether the Cantana is running on the same machines as MPD.  It works if Cantana and MPD running on the same local machine. Otherwise, if MPD is running on a NAS (with music directory set in context of the NAS file system) while Cantana is running on a different machine e.g. laptop, desktop etc. The music directory from the context of the laptop/desktop would be different (i.e. mapped drive f:\Music or in linux /run/user/1000/gvfs/smb-share:server=nasserver,share=music) and could be the reason this doesn't work.
