### ISSUE TITLE
Album artwork does not display in top bar, but displays in playlist

### ISSUE THREAD

**Issue by danarnold** [CDrummond/cantata#1265]
<img width="1316" alt="screen shot 2018-05-04 at 1 31 58 pm" src="https://user-images.githubusercontent.com/1298123/39642394-a519757a-4f9f-11e8-87a3-fb8230832244.png">

This started happening when I switched from v2.0.1 to v2.3.0 (current).

**Comment by CDrummond** [comment]
Odd, as its working fine for me. Just tried on mac, and again cover is retrieved. 

Does it ever work for you? Is it only some album covers, or all? What about if you restart Cantata, does it then show the cover? What about if you expand the artist on the left view (so that the cover is shown there), does that make the cover appear in the toolbar?

p.s. which macOS version? As the titlebar and toolbar should be unified (and are for me).

**Comment by danarnold** [comment]
It seems to have actually just been that album, although I could have sworn it was affecting other albums. I tried right-clicking the album on the left view and setting the image again, and that time, it worked; I think it may have just been an issue with the auto-fetching for this particular album.

I'm on macOS 10.13.4. I'm not sure what you mean by the titlebar and toolbar being unified, do you mean they should be the same color?

Closing this since the issue is solved, but if you'd like any other information, I'd be happy to provide it.
