### ISSUE TITLE
modified-since-filter

### ISSUE THREAD

**Issue by h-2** [CDrummond/cantata#1298]
MPD seems to support filtering by file-modification-date. This would be really useful to generate e.g. a "100 most recently added songs" dynamic playlist.

Could something like this be added?

Thanks!

**Comment by CDrummond** [comment]
I can add this, but would a 'Smart' playlist not be abetter match? These are like dynamic playlists, but do not dynamically re-populate the playqueue, and you can control the order of songs added.

**Comment by h-2** [comment]
Could not both be possible? 😄

**Comment by CDrummond** [comment]
Yes - it is possible to add to dynamic playlists. **But** this would not allow "add 100 most recent" - because the order is random. You cold only add a restriction that all chosen songs be within this window. A smart playlist allows you to add 100 songs added within the last X days and sorted by modification time. 

i.e. if you had 200 songs bought in the last 30 days - a dynamic playlist (set to add 100 at a time) will add a mix of tracks, in no defined order. So you would not get the 100 most recent first.

For this reason, I'm not convinced this option makes sense for a _dynamic_ playlist.

**Comment by h-2** [comment]
Cool, thanks!
