### ISSUE TITLE
[Feature request] More configuration for the play queue

### ISSUE THREAD

**Issue by mercuryrw** [CDrummond/cantata#1310]
Love Cantata, but would be great if users could change the default action for double clicking a track. I usually prefer to "Play Now" instead of "Append" so it'd be great if there was a toggle for that in the settings.

Also, when you press "Play Now" is it possible to enqueue the whole album and then automatically jump to the track you selected. 

E.g. if you select "Track 3" from an album, the play queue will look like this:
_Track 1
Track 2
Track 3 (playing)
Track 4
Track 5_

Instead of just:
_Track 3_

This means that once that track is finished, the rest of the album continues to play. Again, a toggle in the settings would be great for this.

I've had a look at the code, but wouldn't really know where to begin trying to implement these features.
Thanks, Richard.

**Comment by CDrummond** [comment]
Setting double-click behavior seems easy, and a reasonable idea. Will do for 2.4

As for clicking on an action. When you click one of the action buttons, the selection is actually cleared. So, at that point Cantata no longer knows that you had multiple items selected. So, without a major re-work (which I'm not going to do), this is not possible.

**Comment by mercuryrw** [comment]
Oh no, that's not what i mean. It's nothing to do with multiple items selected. What i mean is that if i choose to play a single track in an album, it will do the following:

1. clear the current play queue
2. enqueue the entire album that the track you selected belongs to
3. play the track you selected e.g. track 4 from that album

The reason I think this would be good is that once the track is finished, the rest of the album will continue to play, instead of you having to select the next track manually.

Lots of popular music players seem to do it this way, e.g. musicbee, itunes, shuttle for android.
Just thought it might've been something to look into :)

**Comment by Nocifer** [comment]
While I agree this could be a nice feature, you can achieve, like, 70% of it already by just queueing the album folder instead of a specific song. After all, when you want to listen to the whole album you usually want to begin with the first song. But, since it's not "always" but "usually", as I said I think it would be a nice addition. Could go something like this:

1. Select song, send it to play queue.
2. Cantara, instead of loading only that specific song, loads the entire folder the song is in.
3. It then begins playing with the song you actually had selected.

But I think what CDrummond may have meant was that, as it currently is, Cantara would not have the means to remember your initial selection after going up the hierarchy and loading the parent folder - it would only remember the "thing" that triggered the "put on queue" action, and that "thing" would at that point be the parent folder, so afterwards it couldn't know which song you actually wanted it to play.

But on the other hand, I could be completely wrong :P

**Comment by mercuryrw** [comment]
@Nocifer yea it's nothing major, the current system seems to work for most people so it's probably not worth a rework just yet.

**Comment by CDrummond** [comment]
Thinking about this, it seems overkill to add another config option. I could see the need if double-click worked on artist/albums. But, for tracks? I'm happy with leaving append be the default action.
