### ISSUE TITLE
Podcasts stop working while listening

### ISSUE THREAD

**Issue by cyberking1** [CDrummond/cantata#1322]
Hi, 

       I love the podcast support in Cantata but when I am listening to a podcast for a certain period of time the podcast stops playing and I have to restart the podcast and put it back where it left off. I am using the latest version of Cantata 2.3.1 on Kubuntu 18.04, If I download a podcast in Cantata and listen to it that way the podcast plays just fine the issue is trying to listen to podcasts while streaming them over the internet using Cantata. I have tried using Clementine to listen to podcasts while streaming and they work just fine without it stopping or dropping off.  

Thanks for any help.

**Comment by CDrummond** [comment]
Are these downloaded podcasts? As in have you used Cantata to download them?

Cantata does not play the podcast. It simply passes the podcast URL to MPD. It is MPD that then performs the playback.

If you have downloaded them, then MPD gets the MP3, etc, stream from Cantata. Otherwise it gets it direct from the podcast provider.

So, if you are not playing a donwloaded podcast - the issue is not in Cantata.

**Comment by CDrummond** [comment]
OK, just re-read your very long line. So, downloaded podcasts work. Here Cantata is serving the podcast file to MPD. The case that does not work - playing back from the remote server - is all handled by MPD. Cantata simply gives the URL of the podcast to MPD, and tells MPD to play. Sorry, nothing Cantata can do here. Issue is either with MPD, or your setup.

**Comment by cyberking1** [comment]
Hi,

          I believe the setup is correct, everything else works fine and
Cantata and MPD are set up by default by the Kubuntu team.  Cantata and MPD
play music great! but listening to podcasts that are being streamed stop
after a while. Would reinstalling MPD fix the issue?.
