### ISSUE TITLE
[Feature Request] webm tagging support

### ISSUE THREAD

**Issue by SpineEyE** [CDrummond/cantata#1330]
How difficult do you think it is to add [webm tagging](https://www.webmproject.org/docs/container/#tagging)? I found [this library](https://github.com/zaps166/libsimplewebm) that seems to have basic support for it.

**Comment by CDrummond** [comment]
To be honest, I have no time (nor need) for this. Does MPD even support webm audio playback? Where do you get webm audio files from? Also, tagging is done via TagLib - so that would also need to support webm. and (AFAIK) it does not.

However, should you wish to implement this yourself, I will gladly accept patches / pull requests.
