### ISSUE TITLE
Tray icon disappears randomly under LXQt

### ISSUE THREAD

**Issue by tsujan** [CDrummond/cantata#1390]
**Bug Description**
Since I upgraded it to cantata-git-2.3.2.r13.gd932126e1 from AUR, Cantata's tray icon randomly disappears from LXQt's notification area, which implements https://www.freedesktop.org/wiki/Specifications/StatusNotifierItem .

I've seen no other app having this behavior and Cantata didn't have it before the above-mentioned version (I use Cantata for years).

**To Reproduce**
Sorry, it happens randomly and I haven't found a pattern.

**Expected behavior**
The tray icon should be stable like it was until recently.

**Additional context**
When the tray icon disappears, nothing bad happens -- the music continues -- and it'll show up again if Cantata is launched (most of the time, it'll be stable after that).

P.S. This has nothing to do with https://github.com/CDrummond/cantata/issues/1089. Apparently, that report was about the old systray, which the reporter mistakenly used instead of the notification area.

**Comment by tsujan** [comment]
The previous version I used was cantata-git-2.2.0.r38.g2945e2da and its tray icon was stable, as with the versions before it.

**Comment by CDrummond** [comment]
No idea what''s wrong on your system - I suspect Qt cannot find the icon in the theme. Is there space for Cantata's icon (i.e. menu shows when clicked), but just no icon? i.e is it that the item is not in the tray, or that it's there but without an icon?

However, I have just tested under GNOME with QT_QPA_PLATFORMTHEME  set to gtk2 and qt5ct, and with XDG_CURRENT_DESKTOP set to lxqt. 

Qt's platform abstraction handles the creation of the system tray icon. Both gtk2 and qt5ct support this, the QGnomePlatform does not. Cantata (and Qt) uses XDG_CURRENT_DESKTOP to determine which DE is being used. Not sure what the XDG_CURRENT_DESKTOP setting for LXQt is, but it does not matter - as Cantata only modifies its behavior for KDE and GNOME. 

So, as stated this works. Even if there was an error - I strong suspect it'll be a QSystemTrayIcon, platform theme, or desktop issue.

I have looked at the  code changes between 2.2.0 and current master, and there is nothing that would cause it to stop functioning. There is a slight change so that Mac/Win always use the coloured icon. But for Linux the only changes are; Cantata no longer looks for a cantata-panel icon, but (under GNOME) it does look for cantata-symbolic, falling back to the main icon.

**Comment by tsujan** [comment]
> What is XDG_CURRENT_DESKTOP set to?

`LXQt`

> If you launch Cantata with XDG_CURRENT_DESKTOP=LXQt cantata does the icon always appear?

Yes, the icon always appears at startup. I think (but I'm not 100% sure) that this happens only when I quit Cantata, start it again and forget about it, although I did so today and the icon doesn't want to disappear ;)

I suspected tooltips not based on rational reasoning but just because if I quit and restart Cantata, the tooltip will just say "Cantata" until the track is changed -- not sure if that happened before but I should have seen it if it did...

I think this is one of those issues, whose cause can't be found easily; when you want to see it, it hides.

**Comment by tsujan** [comment]
Don't waste your time on this! I'll tell you if if it happens again. I can even suspect KWin (which I use with LXQt) and its effects. There are too many factors.

**Comment by CDrummond** [comment]
OK, I'll close for now. However, even if it happens again - not sure there is much I can do - the tray item code is trivial.

**Comment by tsujan** [comment]
It hasn't happened since 2 days ago (KWin is upgraded among other things).

**Comment by tsujan** [comment]
OK, this isn't (only) about the tray icon. I didn't encounter it in the last 7 days but, now, something interesting happened: I started Cantata, played it and then, all of a sudden, *its whole window and tray icon disappeared together.* The music wasn't interrupted and the window+tray-icon reappeared when I launched Cantata again.
