### ISSUE TITLE
MPD HTTP stream playback unreliable, choppy or silent

### ISSUE THREAD

**Issue by psy-q** [CDrummond/cantata#1392]
**Describe the bug**
In Cantata 2.0.1 as shipped in e.g. Debian 9, HTTP stream playback is very reliable and fast. There is no discernable buffering and the playback continues into the next song when skipping songs.

In 2.3.2 however, playback stutters when first starting to play a stream, if the stream plays at all. It is plagued by pauses of up to several seconds before buffering enough to play back reliably. However, pausing and resuming playback or skipping songs can frequently mess up the playback so that only silence is heard.

An instance of mpv playing the same stream URL shows no such issues.

**To Reproduce**
1. Configure HTTP streaming in your MPD instance, normalize output to 44.1 KHz (variable resolutions can sometimes cause problems with stream playback)
2. Configure the stream in Cantata 2.0.3
3. Start MPD playback, play the stream, skip songs, pause and resume. Observe that the streaming response is nearly instant and without issues. Stop playback.
4. Configure the same source in Cantata 2.3.2
5. Start MPD playback. Observe that there is no audio, choppy audio or frequent dropouts for some time (e.g. 30 seconds).
6. Once playback has become continuous, pause playback, resume playback, skip songs. Observe that after some skipping, sometimes no more audio plays.
7. Open the stream in another player, e.g. mpv. Pause, resume and skip via some other MPD client. Observe that it plays, skips and pauses fine.

**Expected behavior**
Playback via stream should start and stop relatively quickly and without choppy passages or loss of audio, as it did in 2.0.3. Skipping songs should be reliable and stream playback should not be interrupted.

**Version Info**
 - OS: Debian 9.5 vs. Debian 10 (buster)
 - Cantata Version: 2.0.3 vs. 2.3.2 
 - MPD Version: 0.19.21

**Additional context**
The problem appears both with FLAC and with MP3 streams.

**Comment by CDrummond** [comment]
I'm guessing this is a libVLC vs QtMultimedia issue. Older (Linux) versions built with libVLC by default, 2.3 changes this to QtMultimedia. Try building with libVLC, does this improve the situation? If so, then the issue is with QtMultimedia. Also, try building git/master (with QtMultimedia, to see if any recent changes have helped)

I'm, once again, seriously thinking of removing this feature. I did not code this, and have never used it. I hate the delay between pressing a button and playback. There are just too many issues with a feature I have no use for.

**Comment by psy-q** [comment]
OK, I will try to build it that way. I was attracted to Cantata because I couldn't find any other player with this feature and I always stream music from my NAS at home to wherever I am using it, but I'd understand if it gets cut because it's unused. Not that hard to open an instance of VLC or mpv next to Cantata.

**Comment by mbouron** [comment]
I'm also using cantata because it includes this feature (http playback) and why I proposed a fix for it. As @CDrummond said, using master which includes f8a8a5bb2d545c87d7d506968c11b730a79326f9 should really help. I use it daily without issues. This fix should probably reaches the linux distributions by a backport to an older release or a new release of cantata.

I am considering doing more cleanups over the httpstream code if that helps keeping the feature.

**Comment by CDrummond** [comment]
I plan to release 2.3.3 soon - well as soon as I've fixed the remaining bugs. **Please** feel free to make any cleanups to the http stream code. As stated, its not code that I originally created, and is not a feature I use. If you have any suggestions/fixes - feel free to implement.

I'd like to release 2.3.3 in a week or so - just to get it out of the door.

**Comment by psy-q** [comment]
Sorry, took me a while to get a Qt5 build environment up. It seems that the current master (acecc90) has much fewer issues. No dropouts, no silence, stream playback picks up reliably. There might be slightly longer delays but that could also be because I'm connected via LTE right now.

@mbouron Thanks for keeping the feature alive, and thanks @CDrummond for making such a nice player, it combines all the things I'm looking for and I would have continued using it regardless, even if I'd have to play the HTTP stream separately.
