### ISSUE TITLE
Please add support for "Label" field

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#1465]
Hi,

Looks like MPD quietly enabled "Label" (aka Publisher) in their list of supported tags (https://github.com/MusicPlayerDaemon/MPD/commit/fbea965c70df39fbf649db71d3d37a0e0b108e25). Any chance this could be added to the supported tags for search and display?

Thanks...

**Comment by CDrummond** [comment]
Why would you want to search by Label? This should be possible using 'Any', so I'm not keen on adding another filter - I see no need for this (apart from 'because you can').

The only place where I think it makes sense to display is in the context view - and it already appears there, as this shows all tags.

**Comment by nousernouser** [comment]
Well... I did other tests, and I have found is that the problem seems to be related to 'Performer'.

To reproduce: 

- 'Composer' set in the "Composer Support" tweak.
- 3 albums, genre Classical, same artist/composer
    - 1 (say album **A**) with tracks where the performer tag is set DIFFERENTLY from artist/composer (please note that this is a quite common situation with classical music)
    - 1 (say album **B**) with tracks where the performer tag is set the SAME OF artist/composer
    - 1 (say album **C**) with tracks where the performer tag is NOT set

(see the attached screenshots)

In the now playing (info) view, when playing a track either from album A or B or C, **only** the album A is listed (being album B and album C not listed).

So it seems to be an issue that presents itself only in these circumstances, which however are very common for those who also listen to classical albums!

I hope this can be helpful in identifying the problem, and I hope you will kindly work on it.

Thank you a lot!
Regards

![albumABC](https://user-images.githubusercontent.com/35839588/54078016-3a8dbe80-42c1-11e9-99cc-7d3c215bb257.png)

![infoview](https://user-images.githubusercontent.com/35839588/54078023-49747100-42c1-11e9-92fc-d907a4dc5109.png)
