### ISSUE TITLE
Playing files with a high resolution cover art freezes the UI for a couple of seconds

### ISSUE THREAD

**Issue by MartynasJanonis** [CDrummond/cantata#1466]
**Describe the bug**
Pressing 'play' on a track or album with a high resolution image causes the UI to freeze for a couple of seconds. After the initial freeze everything goes back to normal.

**To Reproduce**
1. Open Cantata
2. Play an audio file with a high resolution cover

**Expected behavior**
UI doesn't freeze.

**Version Info**
 - OS: Linux
 - Cantata Version: 2.3.3
 - MPD Version: 0.21.5

**Additional context**
Cover art's resolution is 3619 x 3024.

Maybe the solution would be to cache a lower resolution image permanently?

**Comment by CDrummond** [comment]
To be honest, I looked into changing the code so that it scales the 'current cover' - but just too much work for a problem I dont have. I no longer actively use Cantata or MPD (switched to LMS years ago). So, not worth my time to look into this - so for me, I'm marking this as 'wontfix' However, please feel free to submit a pull request.

As a work-around for your situation;

a. Set Cantata to use (e.g.) 'cover-scaled' (no extension) as its cover filename.
b. For each of your large covers, create a smaller (e.g. 800px) version called 'cover-scaled.jpg' (or png)
c. When Cantata is looking for a cover, it will look for 'cover-scaled.jpg', 'cover-scaled.png', and then look for the 1st image in the albums folder.
