### ISSUE TITLE
Broken original year tag

### ISSUE THREAD

**Issue by Seqularise** [CDrummond/cantata#1470]
**Describe the bug**
Cantata doesn't display original year value in queue and playlist

**To Reproduce**
Tag files with Picard, import it in Cantata

**Screenshots**
![2019-03-20__17-28-42](https://user-images.githubusercontent.com/32341190/54684274-ab40a080-4b35-11e9-957b-661b5ce5fa3e.png)

**Version Info**
 - OS: Arch
 - Cantata Version: 2.3.3-1
 - MPD Version: 0.21.6-1

**Comment by CDrummond** [comment]
Have you configured MPD to use this tag?

**Comment by Seqularise** [comment]
No.
I use cantata in single user mode, thought that cantata would do everything needed for
So, i need to add metadata_to_use “+original_year” in mpd config?
I havent found exact value in https://www.musicpd.org/doc/html/protocol.html#tags

**Comment by CDrummond** [comment]
Cantata's single-user/basic mode is only meant for simple scnearios, and is not configured for all tags (e.g. this, music brainz, artistsort, etc.) to use all of MPDs features, you need to configure MPD yourself.

**Comment by DarkSwan86** [comment]
@CDrummond I have the same exact problem, a collection tagged with Picard and the original year is ignored. Here is an example of the metadata (from the metadata page on Cantata):

Artist: | The Police
-- | --
Album artist: | The Police
Album: | Reggatta de Blanc
Track number: | 1
Disc number: | 1
Date: | 2003
Original date: | 1979-10-05
Label: | A&M Records
Catalogue number: | 493 653-2
Artist sort: | Police, The
Album artist sort: | Police, The
Media: | CD
Tracktotal: | 11
Totaltracks: | 11
Totaldiscs: | 1
Script: | Latn
Releasetype: | album
Releasestatus: | official
Releasecountry: | XE
Originalyear: | 1979

Under Tweaks->Miscellaneous i have selected "Use original year to tag and display..." but still Cantata show me the Year (2003) instead of the original year (1979). I'm missing something about that option? 

Manjaro Linux, Cantata 2.3.3
