### ISSUE TITLE
Hide HTOA (Hidden Track One Audio) files

### ISSUE THREAD

**Issue by DarkSwan86** [CDrummond/cantata#1504]
Hi CDrummond!

Is it possible to implement an option to Cantata to not index the HTOA files? They show up as a duplicate of the original album.

These files are created by programs like EAC, Whipper or CueRipper and they are simply silent files but they are needed when you create a backup of a CD, to preserve the original structure of the disk.

Usually these files are very small, < 20KiB but they are tagged with all the informations from the original CD. 

Here is an example of a CUE backup of "Madcap Laughs" by Syd Barrett:

> REM DISCID 250D6813
PERFORMER "Syd Barrett"
TITLE "The Madcap Laughs"
CATALOG 0077778141228
REM DATE 1970
REM DISCNUMBER 1
REM TOTALDISCS 1
REM COMMENT "CUERipper v2.1.6 Copyright (C) 2008-13 Grigory Chudov"
**FILE "00. (HTOA).flac" WAVE
  TRACK 01 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Terrapin"
    INDEX 00 00:00:00**
FILE "01. Terrapin.flac" WAVE
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "No Good Trying"
    INDEX 00 05:02:55
FILE "02. No Good Trying.flac" WAVE
    INDEX 01 00:00:00
  TRACK 03 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Love You"
    INDEX 00 03:22:10
FILE "03. Love You.flac" WAVE
    INDEX 01 00:00:00
  TRACK 04 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "No Mans Land"
    INDEX 00 02:25:60
FILE "04. No Mans Land.flac" WAVE
    INDEX 01 00:00:00
  TRACK 05 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Dark Globe"
    INDEX 00 02:59:12
FILE "05. Dark Globe.flac" WAVE
    INDEX 01 00:00:00
  TRACK 06 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Here I Go"
    INDEX 00 01:58:50
FILE "06. Here I Go.flac" WAVE
    INDEX 01 00:00:00
  TRACK 07 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Octopus"
    INDEX 00 03:09:05
FILE "07. Octopus.flac" WAVE
    INDEX 01 00:00:00
  TRACK 08 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Golden Hair"
    INDEX 00 03:43:70
FILE "08. Golden Hair.flac" WAVE
    INDEX 01 00:00:00
  TRACK 09 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Long Gone"
    INDEX 00 01:56:32
FILE "09. Long Gone.flac" WAVE
    INDEX 01 00:00:00
  TRACK 10 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "She Took a Long Cold Look"
    INDEX 00 02:46:73
FILE "10. She Took a Long Cold Look.flac" WAVE
    INDEX 01 00:00:00
  TRACK 11 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Feel"
    INDEX 00 01:55:28
FILE "11. Feel.flac" WAVE
    INDEX 01 00:00:00
  TRACK 12 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "If Its in You"
    INDEX 00 02:17:35
FILE "12. If Its in You.flac" WAVE
    INDEX 01 00:00:00
  TRACK 13 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Late Night"
    INDEX 00 02:22:65
FILE "13. Late Night.flac" WAVE
    INDEX 01 00:00:00
  TRACK 14 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Octopus (takes 1 & 2)"
    INDEX 00 03:10:60
FILE "14. Octopus (takes 1 & 2).flac" WAVE
    INDEX 01 00:00:00
  TRACK 15 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Its No Good Trying (take 5)"
    INDEX 00 03:09:17
FILE "15. Its No Good Trying (take 5).flac" WAVE
    INDEX 01 00:00:00
  TRACK 16 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Love You (take 1)"
    INDEX 00 06:22:48
FILE "16. Love You (take 1).flac" WAVE
    INDEX 01 00:00:00
  TRACK 17 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Love You (take 3)"
    INDEX 00 02:28:63
FILE "17. Love You (take 3).flac" WAVE
    INDEX 01 00:00:00
  TRACK 18 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "She Took a Long Cold Look at Me (take 4)"
    INDEX 00 02:11:23
FILE "18. She Took a Long Cold Look at Me (take 4).flac" WAVE
    INDEX 01 00:00:00
  TRACK 19 AUDIO
    PERFORMER "Syd Barrett"
    TITLE "Golden Hair (take 5)"
    INDEX 00 02:44:53
FILE "19. Golden Hair (take 5).flac" WAVE
    INDEX 01 00:00:00

More information [HERE](https://wiki.hydrogenaud.io/index.php?title=HTOA). 

I don't know how hard is my request so thanks in advance if you will ever take in consideration this feature request! :)

**Comment by nousernouser** [comment]
Hi DarkSwan86, 

As I am interested in CUE files, could you better clarify some aspects please?

1. You say "CUE backup": What do you mean? Were you using a folder with audio files in it and the cue file as a playlist with track metadata?

2. If you are using a folder with audio files + a cue file as a playlist with track metadata: 

- Are you sure that the audio files do not have embedded metadata? If so, then the duplication probably derives from this... Given the cue file you have attached, the part relating to the hidden track:

~~~.text
FILE "00. (HTOA).flac" WAVE
TRACK 01 AUDIO
PERFORMER "Syd Barrett"
TITLE "Terrapin"
INDEX 00 00:00:00
~~~

should NOT result from the parsing done by Cantata having no `INDEX 01 ...` command. For this reason it is possible that the duplication derives from the presence of embedded tags in some audio file present in the folder.

- Note also that if there is more than one CUE file in the folder, then Cantata should show an album for each of these, and this could explain the duplication...

3. Is there any way in which a software can recognize an HTOA audio file distinguishing it from a "normal" audio file? Do you know a way in which, in a **standard compliant**  CUESHEET, one can distinguish a FILE command associated with an HTOA audio file from other FILE commands associated with "normal" audio files? 

Please, also allow me a (personal) side annotation: HTAO seems to me yet another non-standard non-compliant so-called "feature" used by programs like EAC and similars (also see: <http://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Multiple_files_with_gaps_.28Noncompliant.29>, <https://web.archive.org/web/20110718230838/http://www.digital-inn.de/exact-audio-copy-english/40013-why-i-hate-eac-malformed-cue-sheets-4.html?s=3ce06844aaaadbf3cdf651003ac6c7bf#post148362>)... 

If it is necessary (as it is also for me) to be able to make a backup copy of the original structure of the disk, why not use accurate and standards-compliant programs (such as cdparanoia. Cdrdao and / or others based on these) and also extract the CD's TOC file (together with the audio file (s) and the CUE file) and then use the later TOC when burning a copy of the CD?

Regards

**Comment by CDrummond** [comment]
@nousernouser Your understanding of CUE files is **vastly** superior to mine. The original code was just copied (and modified) from Clementine. While I have a few cue files, they are all trivial.

To be honest, I have no idea what to do about this request. It is not a feature I see any real need for, and is not something I'd ever use. So, I'm not going to spend anytime on this. But, please feel free - pull requests (as usual) are always welcome.

**Comment by nousernouser** [comment]
Hi CraigD

> @nousernouser Your understanding of CUE files is **vastly** superior to mine.
> The original code was just copied (and modified) from Clementine. While I
> have a few cue files, they are all trivial.

I know... but now Cantata has the best support for CUE files among the
many mpd clients I have tried (thanks again for this!!!)

> To be honest, I have no idea what to do about this request. It is not a
> feature I see any real need for, and is not something I'd ever use. So, I'm
> not going to spend anytime on this. But, please feel free - pull requests (as
> usual) are always welcome.


To be honest, I think what follows:

It would be a matter of implementing something that seems to me specific to the
particular cue files (malformed because they are not compliant with the standard
cuesheet) produced by certain programs (which relax the rules on positioning
FILE commands with respect to the tracks contained and the pregaps).

To do so I guess we can proceed:

- intervening at the "source", that is modifying the parsing of the cue
  files ... but now the parsing code works very well assuming (rightly, in my
  opinion) the respect of the standard: it would be a very big job, and only to
  adhere to questionable pseudo-standards used by some (proprietary) programs...
  therefore I would certainly exclude it

- intervening "downstream", that is identifying the duplicates in the
  library produced by HTOA files, and hiding them... I don't know how or how
  heavy it can be to do... 

Assuming CraigD does not intend to proceed with the 2nd one, in the 1st case I
would see only two possibilities:

- ** if ** there is a ** simple and reliable way ** to recognize the HTOA files
  (or in the file system or in the contents of the CUE file), then you could
  consider these files as invalid, and prevent them from loading in Cantata with
  a simple and easy modification in the CUE parsing -- if **@DarkSwan86** could
  provide the way how to recognize the HTOA files (I do not know how), I
  could try do it and propose a patch (but I suspect this will lead to
  unpredictable behaviors with malformed CUE files having FILE command which
  appear before other commands related with the tracks it contains)

- users should manually (or rather through a script) correct CUE files like
  the one provided by DarkSwan86 and / or use different programs (which in my
  opinion would be the best thing!)

For the record, and just in case it might interest someone:

About the need to be able to make a backup copy while preserving the original
timing structure of the CD, a way I do so is:

- extract the TOC file from the original CD using cdrdao (obviously with a
  reader that supports TOC extraction)
- generate the TOC hash
- extract the audio from the CD using cdparanoia
- generate the CUE file starting from the TOC (in order to preserve the
  timing) with toc2cue
- integrate the album and tracks metadata (CDDB etc) in the CUE file, to be used
  as a playlist 

to burn a copy, I use cdrdao again, with the TOC file extracted from the
original CD, then extract the TOC from the CD backup copy and generate the hash,
finally comparing the two hashes to verify that they match

(In my spare time, I am working on a program to automate all the process, also
querying online CDDBs for metadata and covers...)

**Comment by nousernouser** [comment]
@DarkSwan86

If you have in a folder nothing more than all the album's audio files (including the HTOA file) + just one cue file, then I suspect the duplication comes from metadata (a cuesheet?) embedded in the audio file(s), and in particular in the HTOA file (so that they are used by CueRipper when burnig).

Could you check it?

Then, if it is so, a very simple solution coud be:
- copy the HTOA file from the album folder to another folder,  **externally** with respect to the mpd music folder (so that it will not parsed): so you will keep the HTOA file to be used when you need to burn a backup copy of the CD
- then simply remove **all** the embedded tags in the audio files (including the HTOA file) contained in the album folder: this should avoid album duplication!

Please, let me know.

Regards

**Comment by DarkSwan86** [comment]
@nousernouser i think you're right, i suspect that Cueripper creates a non compliant CUE files because it rip down the HTOA even if it's digitally silent. So i don't think that i can propose any way to distinguish these types of HTOA (that are essentially digital silence on a FLAC file) from a real HTOA. In fact all the CDs that i've ripped with [Whipper](https://github.com/whipper-team/whipper) are all without any HTOA files. In their [features](https://github.com/whipper-team/whipper#features) page they states "**Detects and rips _non digitally silent_ Hidden Track One Audio (HTOA)**". So in the future i think i will use Whipper only for my backups.

About Cantata parsing these HTOA files if i reneame them something like (HTOA).flakbak, and refresh the database, all the duplicate albums are removed, fixing my problem. 

I think this Feature request can be closed! 

Thanks for all the support and explanations @nousernouser and sorry for the noise @CDrummond !
