### ISSUE TITLE
Farmcast Podcast does not play

### ISSUE THREAD

**Issue by onnotasler** [CDrummond/cantata#1511]
I subscribed to several podcasts in Cantata, most of them work fine. The podcast http://farmcast.de/feed/podcast/ however does not play episodes, it only loads a list. When I try to start an episode from Farmcast, I only get a notice that I should configure Cantata so that it can properly connect to the internet. Podcast validators I tried do not show any errors.

**Comment by CDrummond** [comment]
Plays fine for me. Not sure what notice you are referring to. Notice from where??

**Comment by onnotasler** [comment]
Cantata displays a red notice atop the Podcast and Playlist: "Senden des Befehls zu Persönlich fehlgeschlagen - nicht verbunden". Roughly: "Send to Personal failed - not connected", maybe "Send to Home failed" as well.

I can download the song, but in that case I get the error message too once the file is completely downloaded.

**Comment by CDrummond** [comment]
Just looked up that translation - basically Cantata failed to send a command to MPD. In this case "Personal" is the name of the MPD connection, and I assume this was setup in "Basic" mode (where Cantata starts an MPD instance). Not sure why this would be specific to this rss feed though.

Which version of Cantata are you using?

**Comment by onnotasler** [comment]
Cantata 2.3.3-1.5 (from OpenSuse)
Server protocol 0.21.0

**Comment by CDrummond** [comment]
Hmmm... Well that's the latest released version, and I see no changes since that would affect this. However, seeing as I **can** play this feed on my system (using the "Basic" mode as well), then I'm not sure what's wong on **your** system. If I could recreate the issue, then I'd have a btter idea as to what's wrong, but its working for me.

Sounds like your local MPD is not running, or is closing at some point. Can you see an MPD instance running under your username (just before, and after you try to play this feed)?

**Comment by onnotasler** [comment]
I installed a lot of updates last week and again today, and after installing the updates today, Cantata works just fine with this podcast. It seems it was not a problem with Cantata at all, but a mismatch with libraries in between those updates. Thanks a lot for your patience, despite it not being a problem with your program after all!

**Comment by CDrummond** [comment]
No, probs. Gald its sorted now.
