### ISSUE TITLE
Plays files out of order

### ISSUE THREAD

**Issue by ShowyJoey** [CDrummond/cantata#1620]
When an album contains files with different *Album* tags, the playback sorts them by *Album*, not by *Track Number*, so playback is in wrong sequence. User can fix temporarily by going to Menu>Queue tab>Sort By>Track Number, but it only works for that listening session and needs to be repeated every time the album is played. Arrrrrgh. My tags are the way they are for a good reason and I shouldn't have to change them to suit a media player's quirks. NEW TO CANTANA, SEEMS EXCELLENT OTHERWISE. THANK YOU!

**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Version Info**
 - OS: [e.g. Linux, macOS, Windows]
 - Cantata Version: [e.g. 2.3.2]
 - MPD Version: [e.g. 0.20.1]
 - CMake options (other than default):

**Additional context**

**Comment by CDrummond** [comment]
Different album tags ==> different album

**Comment by ShowyJoey** [comment]
*Track Numbers* exist for a reason ==> they dictate user's desired song playback sequence. Cantana ignores and bypasses it in favor of something that makes no sense and no way for user to change the default. Hmm.  Need for Different album tags ==> Need for different media player. Oh well, it was free. OR I could just stop creating compilations that inform what album a track came from... 

CDrummond, would you be so kind as to recommend a different media player that meets my crazy strict requirement for playing albums in *Track Number* sequence? Nevermind. It's prolly ALL the others...

**Comment by CDrummond** [comment]
Cantata **does not** ignore track numbers. **BUT** track numbers relate to their **position within an ALBUM** If you have different **album tags** then Cantata will treat as a different album.

Please feel free to use another player - there are **many** to chose from.

**Comment by ShowyJoey** [comment]
I've used Cantana and can confirm that Cantana **does** ignore track numbers **during playback** in favor of **something else** that **shouldn't get priority by default**.

**Comment by CDrummond** [comment]
When Cantata adds an album to the queue, it uses the **TRACK NUMBERS OF THE ALBUM (duh!!!!).** What other order are you expecting? If I add all albums by AC/DC should I have track 1 from album A, track 1 from Album B, Track 1 from C, Track 2 From A, Track 2 from B. **WTF??????**

Why would you have **DIFFERENT** albums tags from tacks from the **SAME** album.

Cantata does not playback anything - MPD does.

**Comment by CDrummond** [comment]
p.s. I **love** your way of trying to convince someone to make a change to a free, opensource, product in their own free time. No politely explaining a scenario, no detailing why you think something should be some way. Just go for the insults. Way to go...

**Comment by ShowyJoey** [comment]
I did not "just go for insults." In my initial post I reported what I consider a bug. There was politeness and a clear explanation of the problem. I even praised your work. Please revisit above.

My compilation album DOES NOT have track 1 from album A, track 1 from album B, etc. like a bunch of random files dumped into a folder. I've been doing this digital music thing for 20 years, LOL. I have the tags purposely altered to dictate desired playback sequence regardless of what album from which they originated. When I pass this "mix tape" on to others, they can see where a song came from, what year, artist, album cover art, etc. It's nice and fun! Technology! Huzzah!

I've never used a digital media player that prioritized something other than track number by default for playback, so naturally I considered it a bug. Your response was a curt and sarcastic one indicating that you don't have the politeness for others you want from me, then you closed the bug report indicating you don't consider Cantana ignoring the user's desired playback sequence per track number a bug. 

As I said, it's free, and I got what I paid for. 

It was you, CDrummond, who got rude. I took the bait and lowered myself to your behavior. And I regret it. I did not want an internet argument on this fine morning. 

Hopefully GitHub lets this thread remain so others can see how the dev thinks and behaves.

Good day to you.

**Comment by ShowyJoey** [comment]
P.S. When I discover free, open source SW I love I pay the dev. Are you setup for donations? Do you take PayPal?

Good day to you.

**Comment by CDrummond** [comment]
Uh? My original replay, whilst a bit short, was **not** rude. You stated Cantata ignored track numbers "for something that makes no sense". That **was** an insult - no asking why it might be that way, just "makes no sense". I corrected you - as Cantata does not ignore these numbers. Never has, never will.

You are going round in circles. A track number is related to its position in an album. So, if you have tagged a track as a different album, of course Cantata will treat it as a different album. How is ANY media player supposed to know track 1 and 2 are of the same album (so should be in that order), if you give them different album tags? If you have a "mix tape" where you have set the order, then why not just set the album tag the same?

**Comment by ShowyJoey** [comment]
I already explained why the album tag remains as is. So someone can see where a song came from. Again, track numbers should dictate song playback sequence. That's their purpose. Cantana is the first player I've seen that doesn't do it by default (and won't let the user change the default). Sorry, but that's very strange to me. And, yeah, it truly doesn't make sense for the track numbers to not be prioritized by default. We can agree to disagree. 

Take care.

**Comment by ShowyJoey** [comment]
The world is on fire and we're arguing over music file tags. The joke is not lost on me...

**Comment by CDrummond** [comment]
But, track numbers relate to their order in a _collection_. Otherwise they have no meaning. Track 1 is track 1 of something. In music, that something (more often than not) is the _album_. And Cantata does respect the track order of an album. How does Cantata not respect track numbers by default? If you are saying you have a folder of 10 tracks, each with a different "album" tag then that will not work with Cantata. Cantata does not care where tracks are located, it groups by album. 

Cantata, and AFAIK, almost all media players orders by album artist, album, disc, track number.

How are you adding these items that are in the "wrong" order? From the "folders" view (which is a MPD list), from a filesystem view, or from the library (which is grouped by album). If its from the library view, then this would show the same order.

**Comment by ShowyJoey** [comment]
I considered avoiding coming back here, but:

Other players play my "mix tape" compilations just fine in the order of my track numbering. Yours does not. Sorry, but it's true. 

Naturally, I thought it was a bug and I reported it as a bug (and not a feature request). Never wanted an argument, but your quick, sarcastic dismissal of my issue triggered me.

I'm trying a new distro and a new batch of SW and of the recent players I've sampled, I like Cantana the most. It's one of the best, full-featured players I've seen in the Linux world and you should absolutely be proud of it. Truth. It even looks really nice and that's unusual for Linux stuff, which is almost always Plain Jane. But NOTHING is perfect. NOTHING. That's why I posted a bug report because I wanted to see Cantana improve. 

Sorry this hurts your pride.  I keep experiencing this same thing throughout the Linux community. Linux offers a tempting alternative to F'ing  Microsoft and Apple, two huge monopolistic companies that HATE THEIR CUSTOMERS, but there are so many hurdles in Linux I don't know where to begin. When problems are pointed out, Linux devs, more often then not, have this attitude of "It's free, so if you don't like it, go elsewhere". That's not helpful at all. It hurts the Linux brand. Don't you want your product to be the best it can be? I do. If everyone strove to improve, malware like Win10 would die from rejection, but most users won't reject Windows because it's EASIER, even despite all the problems with it. If you ask anyone who tries Linux and then goes back where they came from for their opinion, it's almost always "Everything keeps breaking" or "It's just too confusing" or "It just didn't make sense". I keep sticking with  Linux because of a million reasons, but again and again, members of the community act like they don't want new members in their special, exclusive club, even though newcomers are desperate for an alternative, just like you, and would make the club stronger. It's just contradictory and self-destructive behavior. It's safe to assume you're a Linux dev because you want to create a better alternative, but then you don't listen to what people are trying to tell you, you argue with them...

Track numbers should have **FINAL SAY** in an album's playback sequence, regardless of where the contents of the album came from.

But Cantana defers to something else. Seriously, WHY? Because pride? You can run in circles saying what you want about Albums and Collections and whatnot, but it just doesn't matter. I'm being honest here. Other players don't play my compilations in the wrong sequence. Maybe I edit my tags differently than you do, but so what? Track numbers should get final say of playback sequence. THAT'S THEIR PURPOSE. IT'S WHY THEY EXIST. You even built in the temporary option with Menu>Queue tab>Sort By>Track Number, you just didn't make it the default. Again, WHY?

Come on, dude. You don't become successful just by coding software, you have to listen to the end users when they say there's a problem...

**Comment by Thaodan** [comment]
Before such a rant I'd try other mpd frontends as cantata is "just" a ui for mpd.

**Comment by Thaodan** [comment]
>Come on, dude. You don't become successful just by coding software, you have to listen to the end users when they say there's a >problem...

This project has no end users. You act like you paid for it.

**Comment by ShowyJoey** [comment]
> This project has no **end users**. You act like you paid for it.

No. This project has no CUSTOMERS. I reported a BUG and when the dev argued that a bug isn't a bug I encouraged improvement and stated that I donate to devs for their hard work on freeware. I've PAID for much freeware over the years. I never demanded anything for free. I guess if MPD core features can't be tweaked by subsequent devs I'll avoid other players built upon it in the future. Or, I guess if this dev doesn't see any reason for improvement I'll forget about Cantankerous Cortana because it's too basic and limited for someone who wants to do something a tad more advanced or horribly complex like play songs in track number sequence and display different album covers for different tracks (!) LIKE WALKING AND CHEWING GUM AT THE SAME TIME like other software. 

Sorry I ruffled feathers by encouraging growth. Mediocrity prevails as usual. Disappointed End User out.

**Comment by Thaodan** [comment]
This project isn't freeware.

**Comment by CDrummond** [comment]
Please, give it a rest. Of course there are no customers. I started this for myself, and code it for myself. If others like it, great, if not that is their choice. MPD has many clients - you are free to choose which is best for you. Cantata, as stated on the main github page, is coded purely for fun - never monetary gain. There is only a paypal link because others have asked for this - I have never asked, or actively looked for, monetary contributions. In fact, I previously asked users to donate to local charities instead. And no, this does not make me a saint.

It is not a bug - might not work the way you want, but that does not make it a bug. It works the way I, as the person who created it in their spate time, wants and **designed** it to work. End of. To make a patently false claim that Cantata does not respect track order is not the way to get your 'issue' looked into. Yes I know respecting track order is 'basic' - because it **does** respect track order. The **album track order**.

You have **never** fully explained how you are adding items that get played in the 'wrong' order. It can't be from Cantata's library view - as this groups by album. You have different album tags so they will be shown, in Cantata, in separate groups. I'm guessing its via 'Folders / Server Folders' The order of tracks here comes from MPD. For other views within 'Folders' - these list the filesystem and files are ordered by Qt - so by filename. Cantata adds tracks to the queue in the order shown in these views. MPD then plays tracks in the queue order (unless shuffle is enabled).

The, IMVHO, **vast** majority of users will want a track to have relevance within an album. When adding all albums by an artist onto the queue, they don't want track order to be of precedence - they want album then tracks within album.

Your use case, a mix tape, is **easily** handled by a playlist - and (again, IMVHO) I would have _thought_ this is how _most_ users would create a digital 'mix tape'. This way you would not have even needed to assign a mix-tape-track-number. Or if you are using the filesystem view, if your filenames started with the track number (01 Track A.mp3, 02 Track B.mp3, etc,) Then they would be added in that order. 

And again, stop with the insults - very childish.

**Comment by ShowyJoey** [comment]
Thaodan, "freeware" = free software, so yeah, it's freeware. You seem to just want to contradict. Not helpful.

**Comment by ShowyJoey** [comment]
CDrummond, I literally only wanted to post what I saw as a bug to improve the software BECAUSE I LIKE IT.  Criticism for the sake of criticism was not my intention. 

I explained I make "mix tape" compilations to give to other people. I explained that's why the tags are the way they are. Different Artists, Albums, Years, and a player can display a different album cover art specific to each song. I don't give people playlist files, like M3Us, to people. Those only work when someone has the albums on a device. Yet you tell me I need to change my tags and you school me on playlists. 

Other players handle my files fine, simply sequencing playback by Track Number. I repeatedly asked why Cantana doesn't do this by default instead of being optional (by going to Menu>Queue tab>Sort By>Track Number) and, repeatedly, you've not directly answered the question. You just school me about MPD and Album tags. I don't know why this subject is so touchy, but it apparently is. You've refused to give a simple answer to a simple question.

It's like I say "the sky is blue" and you want to school me that it isn't blue "because MPD reasons".  Saying "Track Numbers should get final say on playback sequence" isn't an offensive thing to say, yet you seem to be offended, as if you're offended the sky is blue. 

You've misunderstood my clear explanations. You've hastily disregarded my issue. You've been rude and hostile from the beginning, arguing in circles then accusing me of doing just that. I've taken your lead, following your sarcasm with more sarcasm, then you call me rude and childish. Seriously, it's like you're just taking hostility out on a stranger on the internet. Even after complimenting your work, multiple times, and thanking you, IN ALL CAPS, you say I just insult. You've taken a small, simple molehill of a problem and turned it into a big, steaming, complex mountain. It's all a bit confounding and it's not worth it. My theory is you see me as just a representation of ALL the people who have ever had any issue with your software or SOMETHING. I am not. I am not Politics. I am not Religion. I am not 9/11. I am not COVID-19. I am not the Whatever It Is You're Really Mad About. I am just a man who tried Cantana. I had one tiny, little issue. And it still isn't resolved. I had one simple, easy question and it still isn't answered. You've been exactly ZERO HELP and this whole process has been INCREDIBLY UNPLEASANT.

If you don't like people using or discussing your software on the internet, maybe it shouldn't be on the internet. Maybe you shouldn't be on the internet.

**Comment by CDrummond** [comment]
> CDrummond, I literally only wanted to post what I saw as a bug to improve the software BECAUSE I LIKE IT. Criticism for the sake of criticism was not my intention.

I will apologise for the very brief reason for closing the issue. As stated on many issues, I no longer use Cantata nor MPD  so I do not have much spare time for this.

In my subsequent reply I stated that Cantata will use the track numbers as their position within an album, and because they have different tags to Cantata they are different albums, so will be sorted in respect to their album, The same as if I added a complete artist to Cantata - it will sort albums, and then track within album. This is also how Cantata sees your mix tape.

> 
> I explained I make "mix tape" compilations to give to other people. I explained that's why the tags are the way they are. Different Artists, Albums, Years, and a player can display a different album cover art specific to each song. I don't give people playlist files, like M3Us, to people. Those only work when someone has the albums on a device. Yet you tell me I need to change my tags and you school me on playlists.

Yes. I know - but you still, even now, have not explained how you are adding these onto the queue. I have tried to explain how and why Cantata is adding them in the order it does. Where it is shown in Cantata (on the left hand side - library, folders, etc.) dictates the order it is added - as the same order there is the order they are (or at least should be) added to the queue.

As to the playlist, I simply meant you could save them as a playlist in Cantata. But a playlist can be in the same folder as the tracks - and you do not need the albums.

/folder
- tracka.mp3
-  trackb.mp3
- playlist.m3u

contents of playlist.m3u:
```
tracka.mp3
trackb.mp3
```

> 
> Other players handle my files fine, simply sequencing playback by Track Number. I repeatedly asked why Cantana doesn't do this by default instead of being optional (by going to Menu>Queue tab>Sort By>Track Number) and, repeatedly, you've not directly answered the question. You just school me about MPD and Album tags. I don't know why this subject is so touchy, but it apparently is. You've refused to give a simple answer to a simple question.

No, I have explained that Cantata adds tracks in album order. I explained, the order in my previous post - and have re-explained in the previous paragraph.

Its not touchy. I am trying to explain to you why it is the way it is in Cantata. The way you use it dictates the way it behaves.

> 
> It's like I say "the sky is blue" and you want to school me that it isn't blue "because MPD reasons". Saying "Track Numbers should get final say on playback sequence" isn't an offensive thing to say, yet you seem to be offended, as if you're offended the sky is blue.

No, I'm stating why my software is acting the way it is. I take offence when someone says something that is wrong - "ignores track numbers" is wrong, and I have explained why many times. Now, I understand you don't like my reasons - fair enough, just use something else then.

Cantata is not, never has been, and never will be, perfect or bug free - I have never stated it was. I have never actively asked for it to be included in any Linux distro. It is a hobby created for fun. For me, not you.

> You've misunderstood my clear explanations. You've hastily disregarded my issue. 

I understand you have a set of tracks - I just don't know how you are adding these to the queue. 

Even if I have "hastily disregarded" the issue - its my free time, and my code.

> You've been rude and hostile from the beginning, 

I have not been rude. You are the one who has resorted to name calling. You keep insisting Cantata ignores track numbers. But this is 100% a lie. It uses track numbers, as when you add an album it sorts those tracks by track number. Therefore it cannot be said it ignores track numbers.

Now yes, when you have this scenario of a collection of tracks with different album tags and track numbers then Cantata sorts by album first and sub-sorts by track number. (Still not ignoring track numbers).

> then you call me rude and childish. 

"LIKE WALKING AND CHEWING GUM AT THE SAME TIME" is not rude and childish? As that was in your own post to which the childish remark was referring to.

> Seriously, it's like you're just taking hostility out on a stranger on the internet. Even after complimenting your work, multiple times, and thanking you, IN ALL CAPS, you say I just insult. You've taken a small, simple molehill of a problem and turned it into a big, steaming, complex mountain. It's all a bit confounding and it's not worth it. 

Then just give it a rest. 

> My theory is you see me as just a representation of ALL the people who have ever had any issue with your software

Most certainly not - one of the worst yes, but no representative of all. Please feel free to read the other 1620 issues on this site.

> or SOMETHING. I am not. I am not Politics. I am not Religion. I am not 9/11. I am not COVID-19. I am not the Whatever It Is You're Really Mad About. I am just a man who tried Cantana. I had one tiny, little issue. And it still isn't resolved. I had one simple, easy question and it still isn't answered. You've been exactly ZERO HELP and this whole process has been INCREDIBLY UNPLEASANT.

You have made this unpleasant. I have no idea why you persist. Its like you think you have some right to dictate to me how to spend my time.

I have been helpful, I have clearly explained why Cantata is acting the way it is. I have repeatedly asked for clarification from you - but you have just ignored this to go round and round in circles.

> 
> If you don't like people using or discussing your software on the internet, maybe it shouldn't be on the internet. Maybe you shouldn't be on the internet.

I'm not stopping you discussing my software, and I have not stopped you commenting on this issue.

> Thaodan, "freeware" = free software, so yeah, it's freeware. You seem to just want to contradict. Not helpful.

Freeware is closed-source software that is free to use. Cantata is open-source - you have access to the source code and can change as you wish.

**Comment by ShowyJoey** [comment]
> My tags are the way they are for a good reason and I shouldn't have to change them to suit a media player's quirks.

That's me in my initial post. I expressed that I couldn't/wouldn't/shouldn't change my tags, that they work fine in other players (which is why I saw Cantana's behavior as a bug). I apologize for the attempt at humor using the word "quirks". The rough, and perhaps rude, stab at humor might have irritated you. *Your response was that I change my tags anyway, then closed the report* , like a door slammed in the face. That definitely irritated me.

I suppose I see no matter in how the files were loaded in Cantana. Either "opened" from a file manager or browsed to from Cantana's menu. Once in the player, the files should do what they should do. Cantana didn't specify how files get loaded leads to a difference in how they're treated. So, how would a newcomer know?

You said it seemed I was dictating how you spend your time. If it seemed that way, I apologize. But I never demanded anything. Not changes to the software. I encouraged improvement so that it could cater to people whose usage scenario might be different than your's or other's, even suggesting donation to the dev. Cantana being included in the SW roundup in my latest distro, I assumed it was something in active development. If I assumed wrong, I apologize. If you can't/won't have the time/inclination to tweak the software, you could have said so at the start. Instead, I got:

> p.s. I **love** your way of trying to convince someone to make a change to a free, opensource, product in their own free time. No politely explaining a scenario, no detailing why you think something should be some way. Just go for the insults. Way to go...

My initial post was a polite explanation of the scenario. Later, I did detail why I think something should be some way: Track Numbers should get final say in the playback sequence. That's their purpose. Said it multiple times. Very clearly. I don't have MULTIPLE ALBUMS queued up in the player. I have ONE ALBUM queued in the player, tracks tagged from different Artists and Albums, but with a single sequence of Track Numbers specifying desired playback sequence. It's dead simple stuff. If you imagined I was doing otherwise, that's your assumption. 

Also, I NEVER "just went for insults". From the beginning, I've complimented and thanked you. Multiple times I've complimented you. You never seem to pick up on that. It's like you filter out the positives and just focus on the negatives, the things I want that you don't want. Saying I just insult is either an oversight or ignorance or a lie on your part so you can "win" a debate/argument. I don't know which.

Seriously, that was more irritating than having the door slammed in my face...

> ...just give it a rest...I have no idea why you persist....

Now you know why. After your first reply, I never, ever, was under the illusion that you were going to change the SW to suit me. 

I never demanded changes to Cantana. I never avoided explaining myself. I never "just insulted". I never called a human being a name. By inferring or outright saying all those things, you've overreacted and misrepresented me nearly every step of the way. I, in turn, overreacted back. In that way, we're not that different. 

I don't care if you reply back. Go ahead and twist things I said, again, intentionally or unintentionally, to get the final say and pretend "victory". I won't be back to overreact to it. Time for both of us to grow the F up.

I regret and apologize for my role in this crap exchange of opinions and attitudes and ego. It has not been my finest hour. CDrummond, I admire your ability to create good software and put it out into the world, something I can't do. I doubt you're a bad person, just flawed like me, like everyone else. Sincerely, I wish you well. Take care.

**Comment by CDrummond** [comment]
> >    My tags are the way they are for a good reason and I shouldn't have to change them to suit a media player's quirks.

> That's me in my initial post. I expressed that I couldn't/wouldn't/shouldn't change my tags, that they work fine in other players (which is why I saw Cantana's behavior as a bug). I apologize for the attempt at humor using the word "quirks". The rough, and perhaps rude, stab at humor might have irritated you. Your response was that I change my tags anyway, then closed the report , like a door slammed in the face. That definitely irritated me.

Um, I **never** said you should change your tags. All I stated was, from Cantata's point of view, different album tag => different album. Plain and simple. Oh, and as I work on this on me free time I will chose which issues to work on, and which not to. There are **many** audio players to chose from - and many that are **much** better than Cantata. (I no longer use Cantata nor MPD)

> I suppose I see no matter in how the files were loaded in Cantana. Either "opened" from a file manager or browsed to from Cantana's menu. Once in the player, the files should do what they should do.

Well, as a user when I see a music player list tracks in a certain order in its browse view I expect them to be added in that order. Why would I expect different? If a music player lists "A, B, C" when browsing for music I expect it to add tracks "A, B, C" in that order when I add that "collection" of tracks onto the queue. Whether the "collection" be an album, a list of artist's tracks, playlist, list of a folders contents, or whatever. Therefore knowing _where_ the list originated from does matter. I would not have asked otherwise.

But you seem unwilling to even entertain that idea.

I know you are not adding multiple albums to the queue - but you are not the only user. So, when I said if a user was to add a folder with 2 albums they'd expect album then track within album order - that was meant to explain that Cantata needs to deal with all situations. So, for yours it appears its not how _you_ would like it. But, if you will not entertain the idea of explaining _how_ your tracks are added to the queue its hard to know where any error _might_ be.

Cantata lists music sources on its left hand pane. These are:

1. Library. Groups tracks by "Genre, Album Artist, Album, Disc, Track Number", or "Ablum Artist, Album, Disc, Track Number", or just "Album, Disc, Track Number". Order of tracks here is controlled by Cantata, and track numbers are used _within_ the album.
2. "Folders/Server Folders" this shows the MPD view of files/folders - the order of tracks here is controlled by MPD, Cantata has no control over this.
3. "Folders/Home" or "Folders/Root" This shows real folders on your Linux installation. Here tracks are sorted by their filename.

So, you can see the order that will be used for tracks when adding by one of Cantata's browse views. The only other way you can get tracks onto the queue is via drag'n'drop. For d'n'd Cantata does not know the track number, so files are added in the order passed.

Now, you have never explained which one of those you are using - despite me asking.

> Cantana didn't specify how files get loaded leads to a difference in how they're treated. So, how would a newcomer know?

It shows the order of the tracks on the left in the browse view. That's a pretty strong hint to the user that they will be added in this order. In the nearly 10 years of Cantata's existence you are the only user to be confused by that.

> Later, I did detail why I think something should be some way: Track Numbers should get final say in the playback sequence. That's their purpose. Said it multiple times. Very clearly. I don't have MULTIPLE ALBUMS queued up in the player. I have ONE ALBUM queued in the player, tracks tagged from different Artists and Albums, but with a single sequence of Track Numbers specifying desired playback sequence. It's dead simple stuff. If you imagined I was doing otherwise, that's your assumption.

Going round in cicles again. Stating "Track Numbers should get final say in the playback sequence" is not detailing it - thats just restating your position for this specific use case yet again. Track numbers alone cannot have the ultimate say. As mentioned, if you have 2 albums in the queue you cannot sort by track number alone. If they are tagged with different album tags they cannot be from one album. One "collection", but not one album. (I know you only have one album, but Cantata is not just for you so has to handle the case of multiple albums). Now, I'm **guessing** but I _assume_ you have 1 folder with all these tracks. But if adding via a directory list - its the order in the folder that matters - to Cantata. Cantata is an MPD client, not a music player - MPD knows the track details, decodes and plays the songs. All Cantata does is pass a list of tracks onto MPD.

> Also, I NEVER "just went for insults". From the beginning, I've complimented and thanked you. Multiple times I've complimented you. You never seem to pick up on that. It's like you filter out the positives and just focus on the negatives, the things I want that you don't want. Saying I just insult is either an oversight or ignorance or a lie on your part so you can "win" a debate/argument. I don't know which.

Comments from you:

(This one from your 2nd post)

> Cantana ignores and bypasses it in favor of something that makes no sense and no way for user to change the default.

> Cantankerous Cortana because it's too basic and limited for someone who wants to do something a tad more advanced or horribly complex like play songs in track number sequence and display different album covers for different tracks (!) LIKE WALKING AND CHEWING GUM AT THE SAME TIME like other software.

Read the above - and if I'd said that to you about a product you've spent nearly 10 years on in your own time for no profit, how would you feel?

Whilst the quote from the 2nd post is not a strong as your subsequent insults, to state that something makes "no sense" is an insult. How can you state that ordering tracks within an album is "something that makes no sense"?

> twist things I said, again, intentionally or unintentionally

If I have twisted things, then I apologise. Never my intention. Still my words have never been as insulting as yours. I agree I can be a bit "short" with my replies, and have already apologised for the original comment that closed the issue.

> to get the final say and pretend "victory".

There is no "victory" - just both of us, I assume, getting a little too involved. 

> I regret and apologize for my role in this crap exchange of opinions and attitudes and ego. It has not been my finest hour. CDrummond, I admire your ability to create good software and put it out into the world, something I can't do. I doubt you're a bad person, just flawed like me, like everyone else. Sincerely, I wish you well. Take care.

And I will accept that. But please, in future when dealing with others - explain things a little more politely, and answer questions when asked, even if the questions seem irrelevant to you. Just because you have a use-case which causes a bit of software to not work they way you would like does not mean that software is defective, it just means its different. If you want developers of open-source software that you use to fix or change things, then you need to be a bit more patient with them. You might only have one issue that you care about, but they have to deal with all other users and issues. And time is short for all.

Just to be clear; I am not stating Cantata is bug free or perfect in any way - its not.
