### ISSUE TITLE
Cantata isn't playing some flac files

### ISSUE THREAD

**Issue by angiioh** [CDrummond/cantata#1630]
**NOTE** Cantata is now in a bug-fix only state. Only bugs that are actual bugs, and not missing functionality will be fixed. Pull requests, however, will still be accepted.
---
---

**Describe the bug**
When I try to play a certain album (Picaresque by The Decemberists in flac) Cantata displays the album in the browser list, but it lists it's track time as 'Unknown' and won't play it when selected and won't let me add it to the queue. This album plays fine in other music players (cmus, rhythmbox)

**To Reproduce**
1. Go to Artist list, scroll down to The Decemberists
2. Click on Picaresque
3. Try to play it
4. Nothing happens, no error

**Expected behavior**
I expected it to play it like my other albums

**Screenshots**
n/a

**Version Info**
 - OS: Linux Mint
 - Cantata Version: 2.4.1
 - MPD Version: 0.21.25
 - CMake options (other than default): n/a

**Additional context**
n/a

Thank you!

**Comment by Thaodan** [comment]
Cantata doesn't play the music, mpd does it. You have to check for any mpd errors.

**Comment by CDrummond** [comment]
As stated by Thaodan, not a Cantata issue.

**Comment by FizzyTea** [comment]
I had a very similar issue, which brought me to this page.

I noticed some multi-artist albums were not being grouped by the set Album Artist tag. I then noticed that if I sorted library view by Album two such albums were given Various Artists and V.A. as artist (they had the record label as Album Artist) but also as OP experienced the track times were 'unknown' and they could not be added to playlist.
Unlike OP I saw using ncmpcpp and mpc that mpd appeared to recognise the tags correctly and have no issue playing them from library.

I then noticed cantata could play tracks if added from browser view as opposed to library view. I also noticed I could not open 'edit track information' if selected through library view but could through folder view,

Since mpd had no database/library issues and read Album Artist as expected I assumed it a cantata issue.
I also found some failure to display some characters in library view (but ok in folder view and track information) and more albums suffering from original issue. Possibly related to this?
https://github.com/CDrummond/cantata/issues/1593#issue-610518757 

Finally I noticed that the affected albums all had a cue file in their directory. 
So I changed the cue file tweak setting from 'Parse in library view, show in folder view' to 'Only Show in Folders View'.
This solved the issues for me.

Hope this was helpful and not irrelevant. Thanks for Cantata!

**Comment by CDrummond** [comment]
@FizzyTea 


> I noticed some multi-artist albums were not being grouped by the set Album Artist tag. I then noticed that if I sorted library view by Album two such albums were given Various Artists and V.A. as artist (they had the record label as Album Artist) but also as OP experienced the track times were 'unknown' and they could not be added to playlist.
> Unlike OP I saw using ncmpcpp and mpc that mpd appeared to recognise the tags correctly and have no issue playing them from library.

Cantata **does** correctly group by AlbumArtist tag - but it **also** uses any musicbrainz tags. If some files have these, and some not, then you will see this issue. But that is not Cantata's fault.

> Since mpd had no database/library issues and read Album Artist as expected I assumed it a cantata issue.

You _assume_ wrong.

**Comment by FizzyTea** [comment]
> Cantata **does** correctly group by AlbumArtist tag - but it **also** uses any musicbrainz tags. If some files have these, and some not, then you will see this issue. But that is not Cantata's fault.
> 

I did not mean Cantata does not correctly group by AlbumArtist tag only that it did not for specific albums. It did it perfectly for most but not for some.
I read about the musicbrainz tags as potentially causing issues and checked that this was not the case. No musicbrainz tags were present.

> > Since mpd had no database/library issues and read Album Artist as expected I assumed it a cantata issue.
> 
> You _assume_ wrong.

Perhaps, but a change in Cantata's settings solved the issues of these songs being in library but unplayable from the library, having an 'unknown' track duration, "ignoring" the albumartist tag and having uneditable (via right click in library view) Track Information.
It was not an mpd issue as mpd was reading the tracks as expected and no changes were made to mpd.
It was not a tag issue as complete retagging (and ensuring no tags such as musicbrainz ones were present) did not solve the issues. 
Instructing cantata to handle cue files differently solved all these issues.

If you are interested - perhaps you are not - the issue may be reproducible by setting the cue file tweak as described and having a cue file in the directory for albums with a) multiple artists and albumartist set and b) albums with single artist but with accents or other "unusual" characters in their albumartist tag (in this case artist and albumartist were the same but the string contained accents on vowels etc)

Anyway I was having a frustrating issue with the Cantata library and solved it by tweaking Cantata settings after trying to solve it looking outside Cantata (at tags and mpd). This issue has similarities to the one in this post and the other referenced post which is still an open issue.
