### ISSUE TITLE
Global Keyboard Shortcuts

### ISSUE THREAD

**Issue by GoogleCodeExporter** [CDrummond/cantata#572]
```
Which version of Cantata?
1.5.0.1

Which build? KDE, Qt4, Qt5, Windows, Ubuntu, Mac?
Windows

What steps will reproduce the problem?
1. Loose Focus from the Cantata Window
2. Now only mediaplayer buttons of my keyboard work, self defined shortcuts 
(like controlling the volume) are only active when the window itself is active

What is the expected output? What do you see instead?
i define the keypress ctrl+VolumeUP in cantata for Volume Up, now i want this 
to function even when cantata is minimized


Please provide any additional information below.

e.g. in foobar2000 you can define each keyboard shortcut as a "global" shortcut 
that would be a good solution

additionally i have the problem that other programs steal my mediaplayer 
buttons functionallity but i can not reproduce that constantly

P.S.:
Thank you for this wonderful mpd client, i use mpd for many years and its 
nearly the client i ever dreamed about :)

```

Original issue reported on code.google.com by `jonas.go...@googlemail.com` on 29 Oct 2014 at 12:04

**Comment by CDrummond** [comment]
Closing for now. I'll happily accept a merge/pull request if someone else feels like implementing.

**Comment by Tormen** [comment]
Hi.

I have 3 questions about this:

(1) This did not change, right ?

I am wondering, because here : https://github.com/CDrummond/cantata/wiki/About-Cantata
it says:
Support for KDE global shortcuts (KDE builds), GNOME media keys (Linux only), and generic media keys (via Qxt support)

But on Archlinux I installed the "Qt5 client for the music player daemon (MPD)" community/cantata 2.0.1-1, which should be a KDE build... and under KDE system-settings shortcuts, global shortcurts, there is no cantata section. Just the media-controller section.

I would like to be able to skip ahead and skip back. Very useful while listening to audio-books.

(2) Now I noticed that there is actually a keyboard shortcut to do that within Cantata (even though it is NOT listed in the Keyboard Shortcut Settings page of cantata (?)): Ctrl + arrow-left / Ctrl + arrow-right

So I wanted to use xdotool to send the keyboard shortcut to cantata. But it does not work. And I don't know why.

Here is what I am trying (I started with ctrl+q because it is very easy to see if it worked ;)):
for win in $(xdotool search  --class cantata); do echo "$win"; xdotool key --clearmodifiers --window $win Ctrl+q; done

And I wonder why it does not work, because just the same works fine with gimp:
for win in $(xdotool search  --class gimp); do echo "$win"; xdotool key --clearmodifiers --window $win Ctrl+q; done

(3) Do you have another idea how one could achieve a global shortcut (meaning a shortcut within KDE, not bound to condition that the Cantata window has to be visible and activated) ?

Thanks a lot in advance!!!

Tormen

**Comment by 56quarters** [comment]
@Tormen 

I was able to replicate this functionality with a combination of KDE "Custom Shortcuts" and the DBus commands supported by Cantata. An example section of my `~/.config/khotkeysrc` file to skip to the previous track (as a global shortcut) is below:

```

[Data_5_1]
Comment=Comment
Enabled=true
Name=Previous Track
Type=SIMPLE_ACTION_DATA

[Data_5_1Actions]
ActionsCount=1

[Data_5_1Actions0]
Arguments=prevtrack
Call=mpd.cantata.triggerAction
RemoteApp=mpd.cantata
RemoteObj=/cantata
Type=DBUS

[Data_5_1Conditions]
Comment=
ConditionsCount=0

[Data_5_1Triggers]
Comment=Simple_action
TriggersCount=1

[Data_5_1Triggers0]
Key=Meta+Z
Type=SHORTCUT
Uuid={8f058bfc-5bbc-4282-998c-42468ed008a0}
```

Hope this helps!

**Comment by Frozen-byte** [comment]
I exported my Custom Shortcut Group for easy import.
[cantataCustom.shortcuts.txt](https://github.com/CDrummond/cantata/files/2188409/cantataCustom.shortcuts.txt)

**Comment by anpaza** [comment]
The above file contains a buggy definition of "prev" track.
Here's a corrected version, with an additonal "stop" action.
The hotkeys may be set up as you like them.
[cantata.txt](https://github.com/CDrummond/cantata/files/2284993/cantata.txt)

**Comment by iangreenleaf** [comment]
In XFCE + Arch Linux, global media keys weren't working for me for some reason, and `cantata-remote` isn't available, so I set up dbus commands through XFCE's Settings->Keyboard->Shortcuts:
![Screenshot_2019-12-30_00-38-02](https://user-images.githubusercontent.com/78887/71570865-f4e2f200-2a9c-11ea-9656-c0c5eaf7abc4.png)

**Comment by vtnpp** [comment]
> In XFCE + Arch Linux, global media keys weren't working for me for some reason, and `cantata-remote` isn't available, so I set up dbus commands through XFCE's Settings->Keyboard->Shortcuts:
> ![Screenshot_2019-12-30_00-38-02](https://user-images.githubusercontent.com/78887/71570865-f4e2f200-2a9c-11ea-9656-c0c5eaf7abc4.png)

Thank you. Can confirm these commands work fine on Arch Linux + KDE Plasma

System Settings > Workspace > Shortcuts > Custom Shortcuts

Action tab:

| Field | Value |
| ----- | ------ |
| Remote application: | mpd.cantata |
| Remote object: | /cantata |
| Function: | triggerAction |
| Arguments: | Any of these: nexttrack - playpausetrack - prevtrack - stopplayback |
