### ISSUE TITLE
Cant build on OS X

### ISSUE THREAD

**Issue by 3marcusw** [CDrummond/cantata#677]
I'm not sure if i'm just making a mistake using Qt Creator, but i followed the README's instructions to build on Mac OS X and i keep getting the following error after i try to build
```
/Users/3marcusw/git/cantata/src/gui/initialsettingswizard.cpp:235: error: use of undeclared identifier 'MPDUser'
        MPDUser::self()->cleanup();
        ^
```

**Comment by CDrummond** [comment]
Sorry - but I only check if master/trunk compiles for OSX/Windows nearer release. This build failure is due to a change that has not been done 100%. However, I'm very busy with the 'devel' branch at the moment  - and don't have time to fix master. I should be ready to merge from devel to master soon - and then I'll get round to fixing this.

For now, I recommend you use a released version.

**Comment by 3marcusw** [comment]
ok. Thanks for all your hard work! This is pretty much the best music player out there.

**Comment by CDrummond** [comment]
The issue you are seeing should now be fixed in master. However, I have not yet tried to compile master for OSX - as master now needs sqlite

**Comment by CDrummond** [comment]
OSX now bulds, but does not run - due to sqlite!

**Comment by CDrummond** [comment]
OSX now builds, but does not look 100% right now. I need to make some adjustments.

**Comment by CDrummond** [comment]
As stated, OSX now builds. UI seems to be OK now - however, still not release ready...
