### ISSUE TITLE
auto pause when cantata window open

### ISSUE THREAD

**Issue by seniorivn** [CDrummond/cantata#692]
Arch linux 
cantata 1.5.2-2
if i open cantata mpd set to pause and "mpc start" work only few seconds, when i close window "mpc play"works fine

**Comment by CDrummond** [comment]
There is no mpc start. Anyhow, mpc play/pause works fine for me with Cantata running - no reason for it not to.

**Comment by seniorivn** [comment]
ok, that's not about mpc, when i press play/pause in cantata it's not work too, about mpc i told because it's used in my keyboard shortcuts.
what logs i can show  to find where is the problem?

**Comment by CDrummond** [comment]
I'm sorry - but this works perfectly. I don't know what the issue is on your side, if there was a fault with simply playing tracks I would have noticed well before now.

Sorry, but I don't have time to debug everyone's setup. If you want debug, run cantata from the commandline as follows:

CANTATA_DEBUG=-1 cantata

this will log all MPD communications.
