### ISSUE TITLE
Choose default settings to skip first boot dialog

### ISSUE THREAD

**Issue by ShalokShalom** [CDrummond/cantata#701]
Currently start Cantata with the question, if i aim to set it up on a local computer or just as client, then comes the question about the path and so on. 

My goal is it, to edit the source code, so that these questions get answered automatic, which let the users explore Cantata in a more direct way and make it more clear for beginners. 

Especially the default selection for the client mode is a tiny thorn in my flesh, since the distro, which aims to use this version of Cantata as the preinstalled music player, focus on complete simpleness for desktop computer user. Who can help me, please ? :)

**Comment by CDrummond** [comment]
See the README for which file to edit, but you can create a default (almost empty) system wide config file - e.g, /etc/xdg/cantata.conf this needs to contain at least:

----------8<------------
[General]
version=1.5.2
----------8<------------

Now when cantata starts, it will think it has already been configured. The only issue is that the window size is not correctly set. This is fixed in master, but not on a release.

**Comment by ShalokShalom** [comment]
Thanks :D
