### ISSUE TITLE
Preferences UI Flashes

### ISSUE THREAD

**Issue by 3marcusw** [CDrummond/cantata#703]
In cantata 1.9.50, which i just built, when I select a tab in preferences, say for example the Interface or Scrobbling tab, the window contents flash repeatedly for about one second and then are normal. This has no functional issues, but makes the interface seem janky.

**Comment by CDrummond** [comment]
Hmmm... I'm guessing this is because of the resizing of the preferences dialog when you change tab? Do most mac apps resize their pref dialog when the tab changes? From my limited experience lots did - and I must admit I didn't like it. The Cantata code tries to mimic this - and seems to work fine under Mavericks.

Does the release 1.5.2 pref dialog also flicker? Just wondering if this is an OS version issue, code version issue, or Qt issue.

**Comment by 3marcusw** [comment]
The 1.5.2 preference dialog did not flicker.

**Comment by CDrummond** [comment]
Can you update master, and try again? If the flicker is fixed can you edit support/confdialog.cpp and change line 58 from 

//#define ANIMATE_RESIZE

to 

#define ANIMATE_RESIZE

...i.e. remove the double / at the start of the line. Rebuild, and try again. Still fixed? Or is the flickering back?

**Comment by 3marcusw** [comment]
yeah, it was fixed. Then i uncommented the line and the problem came back.

**Comment by CDrummond** [comment]
Thought as much. I made two changes, just wanted to be 100% sure it was the animation that was breaking things. Oh well, I'll leave the commented out - never liked it anyway.
