### ISSUE TITLE
HTTPD stream feature request

### ISSUE THREAD

**Issue by mach-o** [CDrummond/cantata#765]
It would be great if Cantata could locally play an mpd http stream. My Cantata client can indeed see the http stream that I've set up on the mpd server, and displays it under the menu option Music » Outputs. But even when selected, Canata doesn't play the stream. To be able to do so, there would have to be a configuration setting to tell Cantata on which port to read the stream on the mpd server. This feature has been implemented in the mpdroid Android mpd client.

**Comment by CDrummond** [comment]
The outputs menu just enables the output - i.e. tells MPD to play music out of this. To *listen* on the HTTP output, you need another app to playback the stream. Cantata *can* do this, you need to pass -DENABLE_HTTP_STREAM_PLAYBACK=ON to cmake when building Cantata. It is disabled by default, as I'm not happy with the delay when pressing play and hearing the stream (due to buffering, etc)

Please, read the documentation before filing bugs/feature-requests.

**Comment by mach-o** [comment]
Thanks for the quick response! Can you point me in the section of the documentation that makes reference to the -DENABLE_HTTP_STREAM_PLAYBACK flag that you're citing, so that I can read it more fully? I wasn't able to locate it.

**Comment by CDrummond** [comment]
INSTALL
