### ISSUE TITLE
Search with Modified disconnects mpd

### ISSUE THREAD

**Issue by alleyoopster** [CDrummond/cantata#767]
Butter up developer to raise chances of getting this fixed: This is the best mpd client

Which version of Cantata?
1.9.50 (git arch linux aur)

What steps will reproduce the problem?
1. Search from Sidebar
2. On left of search bar Click on Artist: and select Modified:
3. Enter a search term 2015 

What is the expected output?
All items modified on date 2015

What do you see instead?
Failed to send command to "Local MPD" (localhost:6600) - not connected

Please provide any additional information below:
Search for 201 works, but add a 5 to make 2015 fails. Same with any 4 digit number eg 1967 fails.  It would be nice to have some idea of date format needed here (and in date search). I tried dd/mm/yyyy and yyyy/mm/dd, but no results. The date search does work with 2015.

**Comment by CDrummond** [comment]
I agree the date format, etc could be clearer - and I'll add a tooltip for this. Cantata attempts to see if the string is a date (yyyy/mm/dd - using ISO format, local format, etc). If the string is less than 7 characters, Cantata assumes its a number of days since today. So 2015 will be two thousand and 15 days ago. This is probably your whole collection, and *MPD* is failing on this - and the collection closes.

Now, Cantata could seta limit of a max of 365 days ago. But still, if you had altered all your files yesterday (e..g set replay gain tags, stc), then a find of 1 day would return the whole collection - and MPD would fail again. I'd say that MPD should be able to handle this gracefully - e.g. by returing nothing, or just a sub-set. Either way this disconnect is NOT a Cantata issue.

The usefulness of the date entry is a Catata issue, and I will work on that.

**Comment by alleyoopster** [comment]
If I try and enter Modified: 2015/11/28 Cantata would still disconnect 
from mpd when I enter the 4th character and before I completed the 
entry. I tried entering the local format which is dd/mm/yyyy, but it did 
not yield any results. The only way I can get this to work is to enter 
number of days.

**Comment by CDrummond** [comment]
As I said, it is MPD that is causing the disconnect - not Cantata.
