### ISSUE TITLE
Playlist not loaded first time

### ISSUE THREAD

**Issue by andreas83** [CDrummond/cantata#781]
my playlist was not loaded from server until i created a new playlist entry via gui

**Comment by CDrummond** [comment]
In what way was it not loaded? Did it not appear in the list of playlists in the sidebar? Was it shown, but had no tracks? Did it not load into the play queue? Does this happen each time you start Cantata?

Which version of Cantata is this with? 1.5.2, or git/master ?

Just tried with git/master and it is working just fine.

**Comment by andreas83** [comment]
Version is 1.5.2 from ubuntu repro

Now i compiled latest version from git, and i see the same issue. 
Stored Playlists are empty, but after i clicked Add to stored Playlist -> New Playlist ...  all other lists stored on my mtp server appear.

**Comment by CDrummond** [comment]
Appear where? In the playlists view in the sidebar, or the context menu? How are you connected to MPD? Via standard socket (e.g. 127.0.0.1:6600), or local socket (e.g. /run/mpd/socket)?

When Cantata detects that the connection has been established to MPD it *should* (and does for me) retrieve the list of playlists from MPD. Please run Cantata from the commandline as follows:

CANTATA_DEBUG=1 cantata

Then once Cantata has started, and connected to MPD, just quit Cantata without doing anything else. This will create a log file - ~/.cache/cantata/cantata.log Please upload this somewhere (e..g use a temp file upload site) - and add a link to that here. This file will contain the communication between Cantata and MPD. (You might want to first check that there is no personal info in this file before uploading).

Also, what version of MPD?

**Comment by andreas83** [comment]
Stored Playlists are empty on the very first run, but after hiting the context menu Playlist -> New Playlist the Stored Playlists are filled up with playlist from server.
Music Player Daemon 0.19.1
Logfile: http://pastebin.com/d5Pzb00G

**Comment by CDrummond** [comment]
When you say playlists are empty - do you mean:

a. The list of playlist names is empty.

or 

b. The playlist names are shown, but not the contents of a playlist

..............

The log file you posted, did you follow the steps I asked? I.e. start cantata, wait until connected, then terminate cantata - without doing **anything** else? Because the log files show that the list of playlists is retrieved. 

..............

Anyway, I've updated the code - so that playlist actions are always enabled, even if the view is hidden. Does it now work?

**Comment by CDrummond** [comment]
Any updates?

**Comment by CDrummond** [comment]
Closing - no updates, and works for me.
