### ISSUE TITLE
Recent Windows downloads are broken

### ISSUE THREAD

**Issue by Hobby-boy** [CDrummond/cantata#789]
On the previous Google Code downloads page on the wiki, google drive reports that they are infected with a virus, and cannot be downloaded. The affected versions are all in the 1.5 and 1.4 sections.

**Comment by CDrummond** [comment]
They are not virus infected - this is just google being sh*t! I even changed from creating the windows installers with inno to nullsoft because of this 'issue' before. Seems to be like their scanner randomly thinks an exe has a virus.

See previous reports: https://github.com/CDrummond/cantata/issues/754

...anyway, I'm working on 2.0 and have no intention of updating any 1.5.x releases/

**Comment by Hobby-boy** [comment]
Would it be possible to reupload version 1.5.2 for windows to another site, like mediafire or dropbox?

**Comment by LordMyschkin** [comment]
just download them with opera or internet explorer - it is not the site that makes the problem.

**Comment by Hobby-boy** [comment]
I've finally been able to redownload it - google drive is no longer reporting a virus in it.
