### ISSUE TITLE
Multiple Regressions in the Search Function

### ISSUE THREAD

**Issue by nuliukas** [CDrummond/cantata#800]
In cantata 2 there is no way to enable search in the _folder view_ anymore. The search view (via MPD) is not an adequate alternative and I see this as a regression, for among other things

1. it does not allow for a directory search anymore;
2. it is incapable of finding, say 'Motörhead' should one submit the query as 'Motorhead'.

In my opinion, latin-extended chars should be interchangeable with their basic latin alternatives. The old search bar in the folder view used to work just fine.

It's a pity to have the old functionality removed, for it used to be my primary method of finding tracks and directories.

**Comment by CDrummond** [comment]
Folder view is dynamically loaded - so cannot search.

**Comment by nuliukas** [comment]
Then do it otherwise. It used to work fine. Was it necessary to break it?

And what about the other 'feature' of the new search? I.e. having no results of 'Mot**ö**rhead' when searching for 'Mot**o**rhead?

**Comment by Goresome** [comment]
What use then have search field in Folders view? Kinda strange to have it there if its not supposed to work, while Library view actually not showing any search fields.

**Comment by CDrummond** [comment]
There should be no search field in the folders view - it should switch to the search page. If the search page does not work for motorhead - thats an MPD issue. If its not working in the Library page, then looks like an issue with SQLite on your system - as it works here.

1.5.2 loaded the *whole* dir structure in one go, this is why search 'worked'. However, it was broken if using MPD's DLNA backend. **DO NOT** assume to tell me to **do it otherwise**

Library view not showing search feidl? What? What do you mean? What search field?

**Comment by Goresome** [comment]
Here what I see after upgrade to 2.0.0
http://i.imgur.com/aQIAy3n.png

Left - Folders view has search field, but it does nothing.
Right - Library view has no search field, that means no way to filter what it shows, user can only scroll through huge list and click.

**Comment by CDrummond** [comment]
Ah, then that indeed is a bug. Ctrl-F in the search page **should**  (and does for me) automatically switch the search page.

Is this from a previous config? The code to show the views and the search is common across all pages. Jsut that when you try to activate search (via the menu entry, or Ctrl-F) it should show the search field for most views, apart from folders.

I as if its from a previous config, as Cantata remembers if the search bar is visible or not - they should be hidden by default.

**Comment by Goresome** [comment]
Yes, this is config from 1.5.5, however I don't remember customizing anything search related and never used Ctrl+F.

It is not clear or me: should Library have search field or not in current implementation? Because if not then Library view is just a special case of Search view, where it shows everything ('*' filter, e.g. empty), on the other hand when I'm browsing through Library and want to limit what it displays by some wildcard I should be able to type some wildcard and immediately see the result. In the current implementation user have to switch to another view to do that.

Can we have Search view show *everything* when search query is empty? It would bring some of the past functionality back.

**Comment by CDrummond** [comment]
They keyboard short-cut Ctrl+F is **standard** for search. When you use this, or select 'Find' from the menu - then the search bar is shown.  This works in most views - just not Folders. These actions (Ctrl-F / menu) are the **same** as in 1.x.

The Library **does** have a search field - and has had for quite some time. It is hidden by default, as it adds visual clutter. Again, this is as it was in 1.x

The Library view is **nothing** like the search view. The library view is a cached copy of the MPD database, that provides grouping of tracks. Currently search does not group (although I'm thinking of adding an option for this).

What functionality is missing? Apart from folder view search - which cannot now work, as the items are loaded on demand (therefore not everything is there to search on).

**Comment by Goresome** [comment]
Right, so I've incorrectly assumed that Ctrl+F in Library will switch me to to Search view, I apologize for not checking that.
Search 'File:' works even better that search in the Folder view did so far, so losing that is no big deal.

**Comment by CDrummond** [comment]
Yeah - the Ctrl+F switching to search view in folders is a work-around for it not having a dedicated search widget.
