### ISSUE TITLE
Paralellel Track Converting: convert a large amount of tracks is horrible slow

### ISSUE THREAD

**Issue by Thaodan** [CDrummond/cantata#809]
When converting a large amount of tracks to copy them to a device for example a smartphone is  horrible slow as cantata converts the track by track.

**Comment by CDrummond** [comment]
Thats the way it is - don't like it then submit a patch.

**Comment by Thaodan** [comment]
Why close it? It's just a suggestion nothing more.  It's still an issue and closing it don't fixes it.

**Comment by CDrummond** [comment]
Because this is **my** project, I'm the **only** one working on it. It is **my** choice as to whether it is an issue or not.

The transcoding, and device copying, code has been single threaded since the very beginning. I personally have no need for transcoding, so am not willing to spend my time on it. Even if I was, I'm not convinced making it a parallel operation would speed things up. The ffmpeg encoding is already using as many threads as possible.

**Comment by Thaodan** [comment]
Oh okay I was just saying my point don't need to be rude. 

Maybe I wrote it wrong cause of my English skills but I guessed it would be possible to convert two or more songs at the time.  Some days ago I tried to convert 300 songs to push them to my phone and it seemed that it took ages. Usually doing such thing wasn't so slow I thought.

**Comment by CDrummond** [comment]
Sorry - I should not take things so personally :-)

I know the device code is not as great as it could be, but it is sufficient for me.

As to the speed, parallel transcodes and copies, will make a difference. I'm just not convinced it will make that much of a difference. If you have 8 cores, and ffmpeg is using all 8 to transcode one file - then I dont *think* multiple instances of ffmpeg will improve things. However, I could be wrong. As I said I will accept patches, etc.

To me this is not an issue - as there is no bug here. It is more of an enhancement request - and for these, I close if I'm not willing to spend time on them.
