### ISSUE TITLE
Switch back to -DENABLE_LIBVLC=OFF on linux by default

### ISSUE THREAD

**Issue by FedeDP** [CDrummond/cantata#810]
Hi!
Archlinux user here. Since cantata 2.0, the package now depends upon libvlc. But libvlc is bundled with vlc on arch, so we have to install vlc to have a working cantata (it sounds pretty stupid, doesn't it?).
Lots of users have tried building cantata 2.0 from aur with -DENABLE-LIBVLC=OFF, and qt5-multimedia works just fine (qt 5.5.1 here).
So, as qt 5.5 is 7-8 months old and qt5.6 is near, can you switch back -DENABLE-LIBVLC to OFF by default on linux too?

**Comment by phantom-code** [comment]
FedeDP, I think it's better to send your request to Arch Linux Cantata's package maintainer: Antonio Rojas <arojas@archlinux.org>

**Comment by FedeDP** [comment]
Already opened a month ago, or so: https://bugs.archlinux.org/task/47888.
I think arojas won't switch until linux default's is -DENABLE_LIBVLC=ON.

**Comment by CDrummond** [comment]
Cantata only uses libvlc, not vlc itself. In Ubuntu these are separate packages - no reason why they cannot be in Arch.

Cantata uses libvlc (or QtMultimedia) to allow playback of MPD's HTTP stream output. Testing with libvlc and QtMultiMedia, I came to the conclusion that vlc as better - less of a delay when playing. Also, I had bug reports due to a gstreamer crash - https://github.com/CDrummond/cantata/issues/770

All this for a feature I've never used...

Anyway, its simple enough to set your own CMake options.

**Comment by FedeDP** [comment]
Ok, thanks. 
On arch bugtracker we already asked for a libvlc split, but we still got no response.
Thank you very much for you work anyway :)
