### ISSUE TITLE
MP3 are listed as playlists and can't be played.

### ISSUE THREAD

**Issue by aahancoc** [CDrummond/cantata#851]
Using the build of Cantata 2.0.0 from OpenSUSE Tumbleweed's community repository (https://software.opensuse.org/package/cantata), every MP3 file shows up as a "playlist". Attempting to play these "playlists" gives an error message saying "MPD reported the following error: Not found." This problem also occurs on Cantata 1.9.x from the same source.

**Comment by CDrummond** [comment]
The track listing comes from MPD. How is it shown as a playlist? In the playlists view? By icon?

**Comment by aahancoc** [comment]
In the "Folders" view, an MP3 file is listed as "[name of file] - Playlist" with the Playlist icon. It looks the same as an m3u file.

**Comment by CDrummond** [comment]
Is this for all files? e.g. if you have the following structure:

artistA/
    albumA/
        trackA1.mp3
        trackA2.mp3
    albumB/
        trackB1.mp3
        trackB2.mp3
        tracks.m3u

Do tracks 'trackA1.mp3' and 'trackA2.mp3' get affected? Or is it **only** in the albumB case - i.e. where there is a playlist in the folder?

Cantata has code that adds a ' -Playlist' to a track's name. The track names in the folder view should come from the track's metadata. Do these tracks have metadata? In order to check if a file is a playlist, Cantata looks at the extension - asx, cue, m3u, pls, and xspf are all treated as playlists. Are your file extensions correct?

**Comment by aahancoc** [comment]
Sorry for the delay. I was away from my Linux computer.

Yes, in that example both trackA* and trackB* would be effected.

These mp3 files play correctly in VLC, mpv, etc. (haven't tried any other MPD-based players yet). It's only in Cantata where they don't work. Most of them have proper metadata, but even those that don't are still effected.

Here's a screenshot of what's going on: http://i.imgur.com/nmsm55n.png
The "02 Unknown" is an OGG file and "Rock You Like A Hurricane.mp3" is an mp3 file. Trying to play the MP3 file acts like playing a playlist, clearing the current song list.

**Comment by CDrummond** [comment]
If Cantata lists "Rock You Like A Hurricane.mp3" as a playlist then this is because MPD has told Cantata that it is a playlist.

Do you connect to MPD via a IP socket? e.g. Do you use hostname (or IP address) and port in Cantata's settings? e.g. I have a local MPD setup on locahost port 6600. If you do, then try the following:

1. Open a terminal window
2. Type:

       telnet localhost 6600

    ...but replace localhost and port if needed
    ...this will connect you to MPD, in a similar way to what Cantata uses.
3. When connected, type:

       lsinfo Scorpions

       Note that "lsinfo" is one word. Scropions is the folder within MPD's music_directory that has the files you want to list. "lsinfo" is an MPD command that should list all files and folders in a folder - along with meta-data (artist, etc) for songs.

4. What does MPD print?


To try to recreate your scenario I have created the following in my MPD music folder:

Wibble/
    Wobble/
        Song A.mp3
        Song B.mp3
        tracks.m3u

The MP3s have no tags, and tracks.m3u just lists the 2 MP3 files without paths. I've then performed the steps I asked of you above:

$ telnet localhost 6600
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
OK MPD 0.19.0
lsinfo Wibble/Wobble
file: Wibble/Wobble/Song A.mp3
Last-Modified: 2016-06-11T08:49:05Z
Time: 402
file: Wibble/Wobble/Song B.mp3
Last-Modified: 2016-06-11T08:49:05Z
Time: 348
playlist: Wibble/Wobble/tracks.m3u
Last-Modified: 2016-06-11T09:16:43Z
OK

Here you can see that the MP3 file lines are prefixed "file:" and the m3u with "playlist:" This is how Cantata knows that a file is a playlist.

**Comment by CDrummond** [comment]
Can you please try the above. Also, please check with another MPD client - e.g. gmpc

**Comment by aahancoc** [comment]
I would use telnet or gmpc, but I can't seem to connect to localhost:6600. ("Connection refused") I'm using whatever "Personal" configuration Cantata set up on first launch, so I'm not sure what the port number would be or how I would figure that out. (Trust me, I've tried. It's part of the reason it took so long for me to respond. Sorry.)

**Comment by CDrummond** [comment]
If you are using 'Personal' then cantata will start its own instance of MPD. Please do the following:

1. cp ~/.cache/cantata/mpd/tag_cache to ~/tag_cache.gz
2. gunzip ~/tag_cache.gz
3. Open ~/tag_cache in a text editor (gedit, kate, vi)
4. Look for one of your MP3s that will not play
5. If should start on a line such as "playlist_begin " or "song_begin" - copy the contents of this until the corresponding "playist_end" / "song_end" to this bug report.

tag_cache is the file MPD writes all song meta data to. Newer versions of MPD compress this file - hence copying it to tag_cache.gz and g-unzipping it.

**Comment by aahancoc** [comment]
Strangely that file had a .gz extension, but wasn't actually compressed. It was just raw text.

Anyways, here's the relevant section:

`directory: A Great Big World
mtime: 1464234154
begin: A Great Big World
playlist_begin: Already Home.mp3
mtime: 1403821696
playlist_end
playlist_begin: I Don't Wanna Love Somebody Else.mp3
mtime: 1403821698
playlist_end
...`

**Comment by CDrummond** [comment]
As you can see by: 

> playlist_end
> playlist_begin: I Don't Wanna Love Somebody Else.mp3
> mtime: 1403821698
> playlist_end

MPD thinks "I Don't Wanna Love Somebody Else.mp3" is a playlist. Not much Cantata can do about this. Sorry, but this looks like there is an issue with MPD on your system (does it have mp3 support?), or this mp3 is in fact a playlist.

**Comment by aahancoc** [comment]
I tried making a new MPD config file and just using GMPC, and the same thing happened. Guess it isn't Cantata after all.

It's strange, because `libmad0` and `lame` are both installed, yet MPD can't find them according to `mpd --version`. Oh well. Thanks for being patient with me.
