### ISSUE TITLE
interacting with the playlist while playing makes it jump to the playing track

### ISSUE THREAD

**Issue by mikelpr** [CDrummond/cantata#922]
precisely that. happens on latest (d545b36)

**Comment by CDrummond** [comment]
How does it 'jump'? Do you mean it scrolls? Try turning off 'Scroll to current track'

When editing the playqueue - Cantata sends the move/delete commands to MPD. MPD then (sometime later) sends an updated playqueue to Cantata. Now Cantata cannot know if this is just because it changed the playqueue, or another client did. Therefore, each update is handled the same. After this update, the playqueue will then center on the current track if the above option is enabled.

**Comment by CDrummond** [comment]
Fixed in master for 2.1.0
