### ISSUE TITLE
Colour scheme issues

### ISSUE THREAD

**Issue by AcarBurak** [CDrummond/cantata#944]
With Cantata 2.0.1 (Qt only) on an Arch/Fluxbox system Qt theme/colour scheme managed by qt5ct,

Issue 1:

Setting Window Text to any colour (tried white and blue) other than black obscures (in Grid view) the hover over icons (Play and Add) as can be seen in the first attachment, cantata.jpg. This is an issue obviously with all the dark(ish) themes with non-black window texts. (With Window Text colour set to black it's as it should be; see the second attachment, cantata2.jpg.

Issue 2:

Only the current track info (in toolbar) follows the Qt theme text colour, others (all the buttons on all the bars) seem to be hardcoded to black which is hard to see in a dark Qt theme as can be seen in the third attachment, cantata3.jpg.

![cantata](https://cloud.githubusercontent.com/assets/1426842/21586197/b8ca2f22-d0d6-11e6-9cd8-41743f77b489.jpg)
![cantata2](https://cloud.githubusercontent.com/assets/1426842/21586198/b8cfcc0c-d0d6-11e6-949c-4c72e5a30b72.jpg)
![cantata3](https://cloud.githubusercontent.com/assets/1426842/21586199/b8d0120c-d0d6-11e6-82a6-fc25d28c7287.jpg)

**Comment by CDrummond** [comment]
This should now be fixed in master - any chance you can checkout and confirm?

This was really 2 issues:

1. Qt5CT does not set its palette immediately, but just after app has started
2. Cantata does not handle palette changes - it never has

So, my change just delays the creation of the main window for 5ms, allowing Qt5CT to set its palette - bit of a hack, but works for now.

**Comment by AcarBurak** [comment]
Well, regarding the first issue, the only difference is that instead of the regular play (▶) and add (✚) signs now I see unrecognized unicode characters (□). No changes in colours.

As for the second issue, instead of black buttons/signs now I have dark grey ones not whites honouring my Qt theme/colours.

To clarify the qt5ct part, I use it as my Qt platform theme set in ~/.bashrc (export QT_QPA_PLATFORMTHEME=qt5ct), so whenever I'd like to change my system-wide Qt theme/colour scheme I launch it and either choose one of the themes I've created previously, or just further customise the current one. All the Qt apps honour my changes immediately.

**Comment by CDrummond** [comment]
If you are not seeing icons, then you have not built/installed correctly. You need to pass -DCMAKE_INSTALL_PREFIX=/usr (or other folder) and do a make install. Cantata 2.x uses 'font awesome' for icons.

The icon colours should come from the colour theme - and do for me. Under KDE, Unity, and GNOME shell.

Do you **only** have the issue with qt5ct?

As stated, Cantata does **not** correctly update when the colour scheme is changed whilst Cantata is running. This is a known issue that has existed since 1.x, that I have no time to fix.

Can you attach your qt5ct colour scheme to this bug report?

Also, which widget style are you using?

**Comment by AcarBurak** [comment]
Sorry, hadn't installed previously and launched Cantata executable from the `build` directory.

Yes, it works now. And relaunching it solves the second (known) issue, so sorry for bothering you with that.

**Comment by CDrummond** [comment]
Ah, so bug fixed?

**Comment by CDrummond** [comment]
Also, can you update, make, and install again? I've made a slight mod so that the work-around is only in place if QT_QPA_PLATFORMTHEME==qt5ct

**Comment by AcarBurak** [comment]
Have installed again and it works fine. So the bug has been fixed, at least for me. Thank you.
