### ISSUE TITLE
Group various artists together

### ISSUE THREAD

**Issue by floli** [CDrummond/cantata#950]
Hello,

I have a lot of compilations, i.e. albums from multiple artists. The AlbumArtist field is set "Various Artists", the Artist field is set to the artist. Both fields are enabled at mpd.

Can I make cantata to group the artists using the AlbumArtist field, so that artists which appear only in a compilation are listed under "Various Artists" and not under their name. It would really unclutter the library view. Amarok does exactly that.

Thanks!

**Comment by CDrummond** [comment]
This is exactly what Cantata does. Cantata groups tracks by:

1. Album Artist - if present and MPD configured to send this to clients, Artist tag otherwise
2. Music Brainz Album ID - if present and MPD configured to send this to clients, Album name otherwise

I have quite a few 'Now XX' albums - all Various Artists. These are correctly grouped.

Sorry, but this is an issue on your system.

**Comment by floli** [comment]
You're right, I was suprised by my own messiness, I apologize.
