### ISSUE TITLE
Artist images for Compilations

### ISSUE THREAD

**Issue by chowbok** [CDrummond/cantata#985]
Cantata has no problem retrieving the artist image with single-artist albums, but at least with my directory setup it can't get the artist for an artist on a compilation (which has the album artist set to "Various Artists"). From the HTTP log it looks like it's only looking for "artist.png" and "artist.jpg" in the root audio directory. It would be nice if there was some way to specify an image in this instance. Maybe albumpath/artistname.jpg? Or a dedicated folder for artist images?

**Comment by CDrummond** [comment]
Well, if you configure Cantata's cover name to have a %, then it would use the AlbumArtist tag for the search. I've now enhanced this so that if the song is Various Artists, then it will use the 'basic artist' name. 'basic artist' changes 'XX featuring YY' to just 'XX'

As to why Cantata looks for the %, this is so that you can specify the cover filename as %album%. It does some substitutions (detailed in README), and removes an remaining % So you could specify the cover filename as %cover. This would then default to just 'cover' for album covers, and use the artist name for artist images from various artist albums.

I know this is not 100% what you are looking for - but I specifically only wanted to make 2 HTTP requests when looking for covers.

**Comment by chowbok** [comment]
I'm totally confused now. Now it's looking for albumartistname.jpg in the root audio directory. I don't want to clutter my root directory with a bunch of loose images; is there a way I can tell it to look for artist images in /rootaudiofolder/Images/artistname.jpg while still getting covers from /albumpath/cover.jpg?
