### ISSUE TITLE
Playing stream only works when MPD is playing at Cantata start

### ISSUE THREAD

**Issue by toaster** [CDrummond/cantata#987]
Hi,

I'm using Cantata 2.0.1 on MacOS and really am happy to have it playing my MPD's stream.

But there are two problems with this functionality:
1. When MPD is not playing music on Cantata startup, the playback does not start when start playing music on MPD. I have to restart Cantata after starting the music on MPD.
2. When _pausing_ music on MPD and continuing it again, the playback doubles the paused time. I guess this is because MPD simply streams silence during the pause while Cantata really pauses the playback and plays the accumulated silence on continue. This guess is supported by the fact that the replay delay (the gap between shown track position and played track position) is raised by the pause time, too.

regards

**Comment by CDrummond** [comment]
1. Not sure what you mean here. But I have configured MPD for a stream output. Configured Cantata to playback this - and checked the headphone icon in the statusbar. No music playing on MPD. Restarted Cantata. Loaded a track, and played. Music is output - although with 2 sec delay because of buffer.

---but after writing the above, I have now seen:

> [00007f977c000b88] core access error: Write error: Connection reset by peer
[00007f977c000b88] core access error: Write error: Broken pipe
[00007f977c000b88] core access error: Write error: Broken pipe
[00007f977c000b88] http access error: failed to send request
[00007f977c000b88] core access error: read error: Connection reset by peer
[00007f977c000b88] http access error: failed to read answer
[00007f977c000b88] access_mms access error: unrecognized chunk FATAL (0x4952)
[00007f977c000b88] access_mms access error: header size == 0
[0000556036077728] core input error: open of `http://127.0.0.1:8000' failed
[0000556036077728] core input error: Your input can't be opened
[0000556036077728] core input error: VLC is unable to open the MRL 'http://127.0.0.1:8000'. Check the log for details.

So, looks like an issue with VLC. Not sure what to really do about this, its not code I wrote - and is not a facility I use. However, its very intermittent - with over 10 play attempts, I only saw this once. But this is on Linux. 

2. How does it double the pause time? If you pause for 1 minute, it pauses for 2??? I assume you mean you paused for a second, but it took 2 to unpause? Again this is the buffer. You can edit Cantata's config (by hand) to **not** pause Cantata's playback of the stream on pause. See the README for Advanced Config items. Not sure where the config is stored on MacOS - I dont use it.

**Comment by CDrummond** [comment]
Thinking about this some more...

1. Guess Cantata thinks MPD has started playback before MPD has created the HTTP output (or enabled it, etc). What I can do is check for failures, and try to open again. Possible in a loop for up to 1 or 2 seconds
2. I guess Cantata should defuaut to not pause playback, but keep playing the silence.

**Comment by toaster** [comment]
That sounds promising. I couldn't find the config file on MacOS. I watched the behaviour with `dtruss` and couldn't see an access to a file in a user specific directory besides the MacOS windows state.

**Comment by CDrummond** [comment]
I've now implemented these two suggestions. I'm going to close this for now, but feel free to re-open if it re-occurs when 2.1.0 is released.
